// ignore_for_file: camel_case_types
// ignore_for_file: non_constant_identifier_names
// ignore_for_file: unused_element
// ignore_for_file: unused_field
// ignore_for_file: constant_identifier_names

// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint, unused_import
@ffi.DefaultAsset('package:dart_notcurses/dart_notcurses.dart')
library;

import 'dart:ffi' as ffi;

@ffi.Native<ffi.Pointer<ffi.Char> Function()>()
external ffi.Pointer<ffi.Char> notcurses_version();

@ffi.Native<
    ffi.Void Function(ffi.Pointer<ffi.Int>, ffi.Pointer<ffi.Int>,
        ffi.Pointer<ffi.Int>, ffi.Pointer<ffi.Int>)>()
external void notcurses_version_components(
  ffi.Pointer<ffi.Int> major,
  ffi.Pointer<ffi.Int> minor,
  ffi.Pointer<ffi.Int> patch,
  ffi.Pointer<ffi.Int> tweak,
);

@ffi.Native<
    ffi.Int Function(
        ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Int>, ffi.Pointer<ffi.Int>)>()
external int ncstrwidth(
  ffi.Pointer<ffi.Char> egcs,
  ffi.Pointer<ffi.Int> validbytes,
  ffi.Pointer<ffi.Int> validwidth,
);

@ffi.Native<
    ffi.Int Function(ffi.Pointer<ffi.Uint32>, ffi.UnsignedInt,
        ffi.Pointer<ffi.UnsignedChar>, ffi.Size)>()
external int notcurses_ucs32_to_utf8(
  ffi.Pointer<ffi.Uint32> ucs32,
  int ucs32count,
  ffi.Pointer<ffi.UnsignedChar> resultbuf,
  int buflen,
);

@ffi.Native<
    ffi.Int Function(
        ffi.Pointer<ncplane>, ffi.Pointer<nccell>, ffi.Pointer<ffi.Char>)>()
external int nccell_load(
  ffi.Pointer<ncplane> n,
  ffi.Pointer<nccell> c,
  ffi.Pointer<ffi.Char> gcluster,
);

@ffi.Native<
    ffi.Int Function(
        ffi.Pointer<ncplane>, ffi.Pointer<nccell>, ffi.Pointer<nccell>)>()
external int nccell_duplicate(
  ffi.Pointer<ncplane> n,
  ffi.Pointer<nccell> targ,
  ffi.Pointer<nccell> c,
);

@ffi.Native<ffi.Void Function(ffi.Pointer<ncplane>, ffi.Pointer<nccell>)>()
external void nccell_release(
  ffi.Pointer<ncplane> n,
  ffi.Pointer<nccell> c,
);

@ffi.Native<
    ffi.Pointer<ffi.Char> Function(ffi.Pointer<ncplane>, ffi.Pointer<nccell>)>()
external ffi.Pointer<ffi.Char> nccell_extended_gcluster(
  ffi.Pointer<ncplane> n,
  ffi.Pointer<nccell> c,
);

@ffi.Native<
    ffi.Int Function(ffi.Pointer<ffi.Char>, ffi.Pointer<notcurses_options>)>()
external int notcurses_lex_margins(
  ffi.Pointer<ffi.Char> op,
  ffi.Pointer<notcurses_options> opts,
);

@ffi.Native<
    ffi.Int Function(ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.UnsignedInt>)>()
external int notcurses_lex_blitter(
  ffi.Pointer<ffi.Char> op,
  ffi.Pointer<ffi.UnsignedInt> blitter,
);

@ffi.Native<ffi.Pointer<ffi.Char> Function(ffi.UnsignedInt)>()
external ffi.Pointer<ffi.Char> notcurses_str_blitter(
  int blitter,
);

@ffi.Native<
    ffi.Int Function(ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.UnsignedInt>)>()
external int notcurses_lex_scalemode(
  ffi.Pointer<ffi.Char> op,
  ffi.Pointer<ffi.UnsignedInt> scalemode,
);

@ffi.Native<ffi.Pointer<ffi.Char> Function(ffi.UnsignedInt)>()
external ffi.Pointer<ffi.Char> notcurses_str_scalemode(
  int scalemode,
);

@ffi.Native<
    ffi.Pointer<notcurses> Function(
        ffi.Pointer<notcurses_options>, ffi.Pointer<FILE>)>()
external ffi.Pointer<notcurses> notcurses_init(
  ffi.Pointer<notcurses_options> opts,
  ffi.Pointer<FILE> fp,
);

@ffi.Native<
    ffi.Pointer<notcurses> Function(
        ffi.Pointer<notcurses_options>, ffi.Pointer<FILE>)>()
external ffi.Pointer<notcurses> notcurses_core_init(
  ffi.Pointer<notcurses_options> opts,
  ffi.Pointer<FILE> fp,
);

@ffi.Native<ffi.Int Function(ffi.Pointer<notcurses>)>()
external int notcurses_stop(
  ffi.Pointer<notcurses> nc,
);

@ffi.Native<ffi.Int Function(ffi.Pointer<notcurses>)>()
external int notcurses_enter_alternate_screen(
  ffi.Pointer<notcurses> nc,
);

@ffi.Native<ffi.Int Function(ffi.Pointer<notcurses>)>()
external int notcurses_leave_alternate_screen(
  ffi.Pointer<notcurses> nc,
);

@ffi.Native<ffi.Pointer<ncplane> Function(ffi.Pointer<notcurses>)>()
external ffi.Pointer<ncplane> notcurses_stdplane(
  ffi.Pointer<notcurses> nc,
);

@ffi.Native<ffi.Pointer<ncplane> Function(ffi.Pointer<notcurses>)>()
external ffi.Pointer<ncplane> notcurses_stdplane_const(
  ffi.Pointer<notcurses> nc,
);

@ffi.Native<ffi.Pointer<ncplane> Function(ffi.Pointer<ncplane>)>()
external ffi.Pointer<ncplane> ncpile_top(
  ffi.Pointer<ncplane> n,
);

@ffi.Native<ffi.Pointer<ncplane> Function(ffi.Pointer<ncplane>)>()
external ffi.Pointer<ncplane> ncpile_bottom(
  ffi.Pointer<ncplane> n,
);

@ffi.Native<ffi.Int Function(ffi.Pointer<ncplane>)>()
external int ncpile_render(
  ffi.Pointer<ncplane> n,
);

@ffi.Native<ffi.Int Function(ffi.Pointer<ncplane>)>()
external int ncpile_rasterize(
  ffi.Pointer<ncplane> n,
);

@ffi.Native<
    ffi.Int Function(ffi.Pointer<ncplane>, ffi.Pointer<ffi.Pointer<ffi.Char>>,
        ffi.Pointer<ffi.Size>)>()
external int ncpile_render_to_buffer(
  ffi.Pointer<ncplane> p,
  ffi.Pointer<ffi.Pointer<ffi.Char>> buf,
  ffi.Pointer<ffi.Size> buflen,
);

@ffi.Native<ffi.Int Function(ffi.Pointer<ncplane>, ffi.Pointer<FILE>)>()
external int ncpile_render_to_file(
  ffi.Pointer<ncplane> p,
  ffi.Pointer<FILE> fp,
);

@ffi.Native<ffi.Void Function(ffi.Pointer<notcurses>)>()
external void notcurses_drop_planes(
  ffi.Pointer<notcurses> nc,
);

@ffi.Native<
    ffi.Uint32 Function(
        ffi.Pointer<notcurses>, ffi.Pointer<timespec>, ffi.Pointer<ncinput>)>()
external int notcurses_get(
  ffi.Pointer<notcurses> n,
  ffi.Pointer<timespec> ts,
  ffi.Pointer<ncinput> ni,
);

@ffi.Native<
    ffi.Int Function(ffi.Pointer<notcurses>, ffi.Pointer<timespec>,
        ffi.Pointer<ncinput>, ffi.Int)>()
external int notcurses_getvec(
  ffi.Pointer<notcurses> n,
  ffi.Pointer<timespec> ts,
  ffi.Pointer<ncinput> ni,
  int vcount,
);

@ffi.Native<ffi.Int Function(ffi.Pointer<notcurses>)>()
external int notcurses_inputready_fd(
  ffi.Pointer<notcurses> n,
);

@ffi.Native<ffi.Int Function(ffi.Pointer<notcurses>, ffi.UnsignedInt)>()
external int notcurses_mice_enable(
  ffi.Pointer<notcurses> n,
  int eventmask,
);

@ffi.Native<ffi.Int Function(ffi.Pointer<notcurses>)>()
external int notcurses_linesigs_disable(
  ffi.Pointer<notcurses> n,
);

@ffi.Native<ffi.Int Function(ffi.Pointer<notcurses>)>()
external int notcurses_linesigs_enable(
  ffi.Pointer<notcurses> n,
);

@ffi.Native<
    ffi.Int Function(ffi.Pointer<notcurses>, ffi.Pointer<ffi.UnsignedInt>,
        ffi.Pointer<ffi.UnsignedInt>)>()
external int notcurses_refresh(
  ffi.Pointer<notcurses> n,
  ffi.Pointer<ffi.UnsignedInt> y,
  ffi.Pointer<ffi.UnsignedInt> x,
);

@ffi.Native<ffi.Pointer<notcurses> Function(ffi.Pointer<ncplane>)>()
external ffi.Pointer<notcurses> ncplane_notcurses(
  ffi.Pointer<ncplane> n,
);

@ffi.Native<ffi.Pointer<notcurses> Function(ffi.Pointer<ncplane>)>()
external ffi.Pointer<notcurses> ncplane_notcurses_const(
  ffi.Pointer<ncplane> n,
);

@ffi.Native<
    ffi.Void Function(ffi.Pointer<ncplane>, ffi.Pointer<ffi.UnsignedInt>,
        ffi.Pointer<ffi.UnsignedInt>)>()
external void ncplane_dim_yx(
  ffi.Pointer<ncplane> n,
  ffi.Pointer<ffi.UnsignedInt> y,
  ffi.Pointer<ffi.UnsignedInt> x,
);

@ffi.Native<
    ffi.Void Function(
        ffi.Pointer<ncplane>,
        ffi.Pointer<ffi.UnsignedInt>,
        ffi.Pointer<ffi.UnsignedInt>,
        ffi.Pointer<ffi.UnsignedInt>,
        ffi.Pointer<ffi.UnsignedInt>,
        ffi.Pointer<ffi.UnsignedInt>,
        ffi.Pointer<ffi.UnsignedInt>)>()
external void ncplane_pixel_geom(
  ffi.Pointer<ncplane> n,
  ffi.Pointer<ffi.UnsignedInt> pxy,
  ffi.Pointer<ffi.UnsignedInt> pxx,
  ffi.Pointer<ffi.UnsignedInt> celldimy,
  ffi.Pointer<ffi.UnsignedInt> celldimx,
  ffi.Pointer<ffi.UnsignedInt> maxbmapy,
  ffi.Pointer<ffi.UnsignedInt> maxbmapx,
);

@ffi.Native<
    ffi.Pointer<ffi.Char> Function(ffi.Pointer<notcurses>, ffi.UnsignedInt,
        ffi.UnsignedInt, ffi.Pointer<ffi.Uint16>, ffi.Pointer<ffi.Uint64>)>()
external ffi.Pointer<ffi.Char> notcurses_at_yx(
  ffi.Pointer<notcurses> nc,
  int yoff,
  int xoff,
  ffi.Pointer<ffi.Uint16> stylemask,
  ffi.Pointer<ffi.Uint64> channels,
);

@ffi.Native<
    ffi.Pointer<ncplane> Function(
        ffi.Pointer<ncplane>, ffi.Pointer<ncplane_options>)>()
external ffi.Pointer<ncplane> ncplane_create(
  ffi.Pointer<ncplane> n,
  ffi.Pointer<ncplane_options> nopts,
);

@ffi.Native<
    ffi.Pointer<ncplane> Function(
        ffi.Pointer<notcurses>, ffi.Pointer<ncplane_options>)>()
external ffi.Pointer<ncplane> ncpile_create(
  ffi.Pointer<notcurses> nc,
  ffi.Pointer<ncplane_options> nopts,
);

@ffi.Native<ffi.Int Function(ffi.Pointer<ncplane>)>()
external int ncplane_resize_maximize(
  ffi.Pointer<ncplane> n,
);

@ffi.Native<ffi.Int Function(ffi.Pointer<ncplane>)>()
external int ncplane_resize_marginalized(
  ffi.Pointer<ncplane> n,
);

@ffi.Native<ffi.Int Function(ffi.Pointer<ncplane>)>()
external int ncplane_resize_realign(
  ffi.Pointer<ncplane> n,
);

@ffi.Native<ffi.Int Function(ffi.Pointer<ncplane>)>()
external int ncplane_resize_placewithin(
  ffi.Pointer<ncplane> n,
);

@ffi.Native<
    ffi.Void Function(
        ffi.Pointer<ncplane>,
        ffi.Pointer<
            ffi.NativeFunction<ffi.Int Function(ffi.Pointer<ncplane>)>>)>()
external void ncplane_set_resizecb(
  ffi.Pointer<ncplane> n,
  ffi.Pointer<ffi.NativeFunction<ffi.Int Function(ffi.Pointer<ncplane>)>>
      resizecb,
);

@ffi.Native<
    ffi.Pointer<ffi.NativeFunction<ffi.Int Function(ffi.Pointer<ncplane>)>>
        Function(ffi.Pointer<ncplane>)>()
external ffi.Pointer<ffi.NativeFunction<ffi.Int Function(ffi.Pointer<ncplane>)>>
    ncplane_resizecb(
  ffi.Pointer<ncplane> n,
);

@ffi.Native<ffi.Int Function(ffi.Pointer<ncplane>, ffi.Pointer<ffi.Char>)>()
external int ncplane_set_name(
  ffi.Pointer<ncplane> n,
  ffi.Pointer<ffi.Char> name,
);

@ffi.Native<ffi.Pointer<ffi.Char> Function(ffi.Pointer<ncplane>)>()
external ffi.Pointer<ffi.Char> ncplane_name(
  ffi.Pointer<ncplane> n,
);

@ffi.Native<
    ffi.Pointer<ncplane> Function(ffi.Pointer<ncplane>, ffi.Pointer<ncplane>)>()
external ffi.Pointer<ncplane> ncplane_reparent(
  ffi.Pointer<ncplane> n,
  ffi.Pointer<ncplane> newparent,
);

@ffi.Native<
    ffi.Pointer<ncplane> Function(ffi.Pointer<ncplane>, ffi.Pointer<ncplane>)>()
external ffi.Pointer<ncplane> ncplane_reparent_family(
  ffi.Pointer<ncplane> n,
  ffi.Pointer<ncplane> newparent,
);

@ffi.Native<
    ffi.Pointer<ncplane> Function(
        ffi.Pointer<ncplane>, ffi.Pointer<ffi.Void>)>()
external ffi.Pointer<ncplane> ncplane_dup(
  ffi.Pointer<ncplane> n,
  ffi.Pointer<ffi.Void> opaque,
);

@ffi.Native<
    ffi.Void Function(ffi.Pointer<ncplane>, ffi.Pointer<ncplane>,
        ffi.Pointer<ffi.Int>, ffi.Pointer<ffi.Int>)>()
external void ncplane_translate(
  ffi.Pointer<ncplane> src,
  ffi.Pointer<ncplane> dst,
  ffi.Pointer<ffi.Int> y,
  ffi.Pointer<ffi.Int> x,
);

@ffi.Native<
    ffi.Bool Function(
        ffi.Pointer<ncplane>, ffi.Pointer<ffi.Int>, ffi.Pointer<ffi.Int>)>()
external bool ncplane_translate_abs(
  ffi.Pointer<ncplane> n,
  ffi.Pointer<ffi.Int> y,
  ffi.Pointer<ffi.Int> x,
);

@ffi.Native<ffi.Bool Function(ffi.Pointer<ncplane>, ffi.UnsignedInt)>()
external bool ncplane_set_scrolling(
  ffi.Pointer<ncplane> n,
  int scrollp,
);

@ffi.Native<ffi.Bool Function(ffi.Pointer<ncplane>)>()
external bool ncplane_scrolling_p(
  ffi.Pointer<ncplane> n,
);

@ffi.Native<ffi.Bool Function(ffi.Pointer<ncplane>, ffi.UnsignedInt)>()
external bool ncplane_set_autogrow(
  ffi.Pointer<ncplane> n,
  int growp,
);

@ffi.Native<ffi.Bool Function(ffi.Pointer<ncplane>)>()
external bool ncplane_autogrow_p(
  ffi.Pointer<ncplane> n,
);

@ffi.Native<ffi.Pointer<ncpalette> Function(ffi.Pointer<notcurses>)>()
external ffi.Pointer<ncpalette> ncpalette_new(
  ffi.Pointer<notcurses> nc,
);

@ffi.Native<ffi.Int Function(ffi.Pointer<notcurses>, ffi.Pointer<ncpalette>)>()
external int ncpalette_use(
  ffi.Pointer<notcurses> nc,
  ffi.Pointer<ncpalette> p,
);

@ffi.Native<ffi.Void Function(ffi.Pointer<ncpalette>)>()
external void ncpalette_free(
  ffi.Pointer<ncpalette> p,
);

@ffi.Native<ffi.Uint16 Function(ffi.Pointer<notcurses>)>()
external int notcurses_supported_styles(
  ffi.Pointer<notcurses> nc,
);

@ffi.Native<ffi.UnsignedInt Function(ffi.Pointer<notcurses>)>()
external int notcurses_palette_size(
  ffi.Pointer<notcurses> nc,
);

@ffi.Native<ffi.Pointer<ffi.Char> Function(ffi.Pointer<notcurses>)>()
external ffi.Pointer<ffi.Char> notcurses_detected_terminal(
  ffi.Pointer<notcurses> nc,
);

@ffi.Native<ffi.Pointer<nccapabilities> Function(ffi.Pointer<notcurses>)>()
external ffi.Pointer<nccapabilities> notcurses_capabilities(
  ffi.Pointer<notcurses> n,
);

@ffi.Native<ffi.UnsignedInt Function(ffi.Pointer<notcurses>)>()
external int notcurses_check_pixel_support(
  ffi.Pointer<notcurses> nc,
);

@ffi.Native<ffi.Bool Function(ffi.Pointer<notcurses>)>()
external bool notcurses_canopen_images(
  ffi.Pointer<notcurses> nc,
);

@ffi.Native<ffi.Bool Function(ffi.Pointer<notcurses>)>()
external bool notcurses_canopen_videos(
  ffi.Pointer<notcurses> nc,
);

@ffi.Native<ffi.Pointer<ncstats> Function(ffi.Pointer<notcurses>)>()
external ffi.Pointer<ncstats> notcurses_stats_alloc(
  ffi.Pointer<notcurses> nc,
);

@ffi.Native<ffi.Void Function(ffi.Pointer<notcurses>, ffi.Pointer<ncstats>)>()
external void notcurses_stats(
  ffi.Pointer<notcurses> nc,
  ffi.Pointer<ncstats> stats,
);

@ffi.Native<ffi.Void Function(ffi.Pointer<notcurses>, ffi.Pointer<ncstats>)>()
external void notcurses_stats_reset(
  ffi.Pointer<notcurses> nc,
  ffi.Pointer<ncstats> stats,
);

@ffi.Native<
    ffi.Int Function(ffi.Pointer<ncplane>, ffi.Int, ffi.Int, ffi.UnsignedInt,
        ffi.UnsignedInt, ffi.Int, ffi.Int, ffi.UnsignedInt, ffi.UnsignedInt)>()
external int ncplane_resize(
  ffi.Pointer<ncplane> n,
  int keepy,
  int keepx,
  int keepleny,
  int keeplenx,
  int yoff,
  int xoff,
  int ylen,
  int xlen,
);

@ffi.Native<ffi.Int Function(ffi.Pointer<ncplane>)>()
external int ncplane_destroy(
  ffi.Pointer<ncplane> n,
);

@ffi.Native<ffi.Int Function(ffi.Pointer<ncplane>, ffi.Pointer<nccell>)>()
external int ncplane_set_base_cell(
  ffi.Pointer<ncplane> n,
  ffi.Pointer<nccell> c,
);

@ffi.Native<
    ffi.Int Function(
        ffi.Pointer<ncplane>, ffi.Pointer<ffi.Char>, ffi.Uint16, ffi.Uint64)>()
external int ncplane_set_base(
  ffi.Pointer<ncplane> n,
  ffi.Pointer<ffi.Char> egc,
  int stylemask,
  int channels,
);

@ffi.Native<ffi.Int Function(ffi.Pointer<ncplane>, ffi.Pointer<nccell>)>()
external int ncplane_base(
  ffi.Pointer<ncplane> n,
  ffi.Pointer<nccell> c,
);

@ffi.Native<
    ffi.Void Function(
        ffi.Pointer<ncplane>, ffi.Pointer<ffi.Int>, ffi.Pointer<ffi.Int>)>()
external void ncplane_yx(
  ffi.Pointer<ncplane> n,
  ffi.Pointer<ffi.Int> y,
  ffi.Pointer<ffi.Int> x,
);

@ffi.Native<ffi.Int Function(ffi.Pointer<ncplane>)>()
external int ncplane_y(
  ffi.Pointer<ncplane> n,
);

@ffi.Native<ffi.Int Function(ffi.Pointer<ncplane>)>()
external int ncplane_x(
  ffi.Pointer<ncplane> n,
);

@ffi.Native<ffi.Int Function(ffi.Pointer<ncplane>, ffi.Int, ffi.Int)>()
external int ncplane_move_yx(
  ffi.Pointer<ncplane> n,
  int y,
  int x,
);

@ffi.Native<
    ffi.Void Function(
        ffi.Pointer<ncplane>, ffi.Pointer<ffi.Int>, ffi.Pointer<ffi.Int>)>()
external void ncplane_abs_yx(
  ffi.Pointer<ncplane> n,
  ffi.Pointer<ffi.Int> y,
  ffi.Pointer<ffi.Int> x,
);

@ffi.Native<ffi.Int Function(ffi.Pointer<ncplane>)>()
external int ncplane_abs_y(
  ffi.Pointer<ncplane> n,
);

@ffi.Native<ffi.Int Function(ffi.Pointer<ncplane>)>()
external int ncplane_abs_x(
  ffi.Pointer<ncplane> n,
);

@ffi.Native<ffi.Pointer<ncplane> Function(ffi.Pointer<ncplane>)>()
external ffi.Pointer<ncplane> ncplane_parent(
  ffi.Pointer<ncplane> n,
);

@ffi.Native<ffi.Pointer<ncplane> Function(ffi.Pointer<ncplane>)>()
external ffi.Pointer<ncplane> ncplane_parent_const(
  ffi.Pointer<ncplane> n,
);

@ffi.Native<ffi.Int Function(ffi.Pointer<ncplane>, ffi.Pointer<ncplane>)>()
external int ncplane_move_above(
  ffi.Pointer<ncplane> n,
  ffi.Pointer<ncplane> above,
);

@ffi.Native<ffi.Int Function(ffi.Pointer<ncplane>, ffi.Pointer<ncplane>)>()
external int ncplane_move_below(
  ffi.Pointer<ncplane> n,
  ffi.Pointer<ncplane> below,
);

@ffi.Native<ffi.Int Function(ffi.Pointer<ncplane>, ffi.Pointer<ncplane>)>()
external int ncplane_move_family_above(
  ffi.Pointer<ncplane> n,
  ffi.Pointer<ncplane> targ,
);

@ffi.Native<ffi.Int Function(ffi.Pointer<ncplane>, ffi.Pointer<ncplane>)>()
external int ncplane_move_family_below(
  ffi.Pointer<ncplane> n,
  ffi.Pointer<ncplane> targ,
);

@ffi.Native<ffi.Int Function(ffi.Pointer<ncplane>)>()
external int ncplane_family_destroy(
  ffi.Pointer<ncplane> n,
);

@ffi.Native<ffi.Pointer<ncplane> Function(ffi.Pointer<ncplane>)>()
external ffi.Pointer<ncplane> ncplane_below(
  ffi.Pointer<ncplane> n,
);

@ffi.Native<ffi.Pointer<ncplane> Function(ffi.Pointer<ncplane>)>()
external ffi.Pointer<ncplane> ncplane_above(
  ffi.Pointer<ncplane> n,
);

@ffi.Native<ffi.Int Function(ffi.Pointer<ncplane>, ffi.Int)>()
external int ncplane_scrollup(
  ffi.Pointer<ncplane> n,
  int r,
);

@ffi.Native<ffi.Int Function(ffi.Pointer<ncplane>, ffi.Pointer<ncplane>)>()
external int ncplane_scrollup_child(
  ffi.Pointer<ncplane> n,
  ffi.Pointer<ncplane> child,
);

@ffi.Native<ffi.Int Function(ffi.Pointer<ncplane>)>()
external int ncplane_rotate_cw(
  ffi.Pointer<ncplane> n,
);

@ffi.Native<ffi.Int Function(ffi.Pointer<ncplane>)>()
external int ncplane_rotate_ccw(
  ffi.Pointer<ncplane> n,
);

@ffi.Native<
    ffi.Pointer<ffi.Char> Function(ffi.Pointer<ncplane>,
        ffi.Pointer<ffi.Uint16>, ffi.Pointer<ffi.Uint64>)>()
external ffi.Pointer<ffi.Char> ncplane_at_cursor(
  ffi.Pointer<ncplane> n,
  ffi.Pointer<ffi.Uint16> stylemask,
  ffi.Pointer<ffi.Uint64> channels,
);

@ffi.Native<ffi.Int Function(ffi.Pointer<ncplane>, ffi.Pointer<nccell>)>()
external int ncplane_at_cursor_cell(
  ffi.Pointer<ncplane> n,
  ffi.Pointer<nccell> c,
);

@ffi.Native<
    ffi.Pointer<ffi.Char> Function(ffi.Pointer<ncplane>, ffi.Int, ffi.Int,
        ffi.Pointer<ffi.Uint16>, ffi.Pointer<ffi.Uint64>)>()
external ffi.Pointer<ffi.Char> ncplane_at_yx(
  ffi.Pointer<ncplane> n,
  int y,
  int x,
  ffi.Pointer<ffi.Uint16> stylemask,
  ffi.Pointer<ffi.Uint64> channels,
);

@ffi.Native<
    ffi.Int Function(
        ffi.Pointer<ncplane>, ffi.Int, ffi.Int, ffi.Pointer<nccell>)>()
external int ncplane_at_yx_cell(
  ffi.Pointer<ncplane> n,
  int y,
  int x,
  ffi.Pointer<nccell> c,
);

@ffi.Native<
    ffi.Pointer<ffi.Char> Function(ffi.Pointer<ncplane>, ffi.Int, ffi.Int,
        ffi.UnsignedInt, ffi.UnsignedInt)>()
external ffi.Pointer<ffi.Char> ncplane_contents(
  ffi.Pointer<ncplane> n,
  int begy,
  int begx,
  int leny,
  int lenx,
);

@ffi.Native<
    ffi.Pointer<ffi.Void> Function(
        ffi.Pointer<ncplane>, ffi.Pointer<ffi.Void>)>()
external ffi.Pointer<ffi.Void> ncplane_set_userptr(
  ffi.Pointer<ncplane> n,
  ffi.Pointer<ffi.Void> opaque,
);

@ffi.Native<ffi.Pointer<ffi.Void> Function(ffi.Pointer<ncplane>)>()
external ffi.Pointer<ffi.Void> ncplane_userptr(
  ffi.Pointer<ncplane> n,
);

@ffi.Native<
    ffi.Void Function(
        ffi.Pointer<ncplane>, ffi.Pointer<ffi.Int>, ffi.Pointer<ffi.Int>)>()
external void ncplane_center_abs(
  ffi.Pointer<ncplane> n,
  ffi.Pointer<ffi.Int> y,
  ffi.Pointer<ffi.Int> x,
);

@ffi.Native<
    ffi.Pointer<ffi.Uint32> Function(
        ffi.Pointer<ncplane>,
        ffi.UnsignedInt,
        ffi.Int,
        ffi.Int,
        ffi.UnsignedInt,
        ffi.UnsignedInt,
        ffi.Pointer<ffi.UnsignedInt>,
        ffi.Pointer<ffi.UnsignedInt>)>()
external ffi.Pointer<ffi.Uint32> ncplane_as_rgba(
  ffi.Pointer<ncplane> n,
  int blit,
  int begy,
  int begx,
  int leny,
  int lenx,
  ffi.Pointer<ffi.UnsignedInt> pxdimy,
  ffi.Pointer<ffi.UnsignedInt> pxdimx,
);

@ffi.Native<ffi.Int Function(ffi.Pointer<ncplane>, ffi.Int, ffi.Int)>()
external int ncplane_cursor_move_yx(
  ffi.Pointer<ncplane> n,
  int y,
  int x,
);

@ffi.Native<ffi.Int Function(ffi.Pointer<ncplane>, ffi.Int, ffi.Int)>()
external int ncplane_cursor_move_rel(
  ffi.Pointer<ncplane> n,
  int y,
  int x,
);

@ffi.Native<ffi.Void Function(ffi.Pointer<ncplane>)>()
external void ncplane_home(
  ffi.Pointer<ncplane> n,
);

@ffi.Native<
    ffi.Void Function(ffi.Pointer<ncplane>, ffi.Pointer<ffi.UnsignedInt>,
        ffi.Pointer<ffi.UnsignedInt>)>()
external void ncplane_cursor_yx(
  ffi.Pointer<ncplane> n,
  ffi.Pointer<ffi.UnsignedInt> y,
  ffi.Pointer<ffi.UnsignedInt> x,
);

@ffi.Native<ffi.Uint64 Function(ffi.Pointer<ncplane>)>()
external int ncplane_channels(
  ffi.Pointer<ncplane> n,
);

@ffi.Native<ffi.Uint16 Function(ffi.Pointer<ncplane>)>()
external int ncplane_styles(
  ffi.Pointer<ncplane> n,
);

@ffi.Native<
    ffi.Int Function(
        ffi.Pointer<ncplane>, ffi.Int, ffi.Int, ffi.Pointer<nccell>)>()
external int ncplane_putc_yx(
  ffi.Pointer<ncplane> n,
  int y,
  int x,
  ffi.Pointer<nccell> c,
);

@ffi.Native<ffi.Int Function(ffi.Pointer<ncplane>, ffi.Char)>()
external int ncplane_putchar_stained(
  ffi.Pointer<ncplane> n,
  int c,
);

@ffi.Native<
    ffi.Int Function(ffi.Pointer<ncplane>, ffi.Int, ffi.Int,
        ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Size>)>()
external int ncplane_putegc_yx(
  ffi.Pointer<ncplane> n,
  int y,
  int x,
  ffi.Pointer<ffi.Char> gclust,
  ffi.Pointer<ffi.Size> sbytes,
);

@ffi.Native<
    ffi.Int Function(
        ffi.Pointer<ncplane>, ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Size>)>()
external int ncplane_putegc_stained(
  ffi.Pointer<ncplane> n,
  ffi.Pointer<ffi.Char> gclust,
  ffi.Pointer<ffi.Size> sbytes,
);

@ffi.Native<
    ffi.Int Function(
        ffi.Pointer<ncplane>, ffi.Pointer<ffi.WChar>, ffi.Pointer<ffi.Size>)>()
external int ncplane_putwegc_stained(
  ffi.Pointer<ncplane> n,
  ffi.Pointer<ffi.WChar> gclust,
  ffi.Pointer<ffi.Size> sbytes,
);

@ffi.Native<
    ffi.Int Function(ffi.Pointer<ncplane>, ffi.Int, ffi.UnsignedInt, ffi.Size,
        ffi.Pointer<ffi.Char>)>()
external int ncplane_putnstr_aligned(
  ffi.Pointer<ncplane> n,
  int y,
  int align,
  int s,
  ffi.Pointer<ffi.Char> str,
);

@ffi.Native<ffi.Int Function(ffi.Pointer<ncplane>, ffi.Pointer<ffi.WChar>)>()
external int ncplane_putwstr_stained(
  ffi.Pointer<ncplane> n,
  ffi.Pointer<ffi.WChar> gclustarr,
);

@ffi.Native<
    ffi.Int Function(ffi.Pointer<ncplane>, ffi.Int, ffi.UnsignedInt,
        ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Size>)>()
external int ncplane_puttext(
  ffi.Pointer<ncplane> n,
  int y,
  int align,
  ffi.Pointer<ffi.Char> text,
  ffi.Pointer<ffi.Size> bytes,
);

@ffi.Native<
    ffi.Int Function(ffi.Pointer<ncplane>, ffi.Pointer<nccell>, ffi.UnsignedInt,
        ffi.Uint64, ffi.Uint64)>()
external int ncplane_hline_interp(
  ffi.Pointer<ncplane> n,
  ffi.Pointer<nccell> c,
  int len,
  int c1,
  int c2,
);

@ffi.Native<
    ffi.Int Function(ffi.Pointer<ncplane>, ffi.Pointer<nccell>, ffi.UnsignedInt,
        ffi.Uint64, ffi.Uint64)>()
external int ncplane_vline_interp(
  ffi.Pointer<ncplane> n,
  ffi.Pointer<nccell> c,
  int len,
  int c1,
  int c2,
);

@ffi.Native<
    ffi.Int Function(
        ffi.Pointer<ncplane>,
        ffi.Pointer<nccell>,
        ffi.Pointer<nccell>,
        ffi.Pointer<nccell>,
        ffi.Pointer<nccell>,
        ffi.Pointer<nccell>,
        ffi.Pointer<nccell>,
        ffi.UnsignedInt,
        ffi.UnsignedInt,
        ffi.UnsignedInt)>()
external int ncplane_box(
  ffi.Pointer<ncplane> n,
  ffi.Pointer<nccell> ul,
  ffi.Pointer<nccell> ur,
  ffi.Pointer<nccell> ll,
  ffi.Pointer<nccell> lr,
  ffi.Pointer<nccell> hline,
  ffi.Pointer<nccell> vline,
  int ystop,
  int xstop,
  int ctlword,
);

@ffi.Native<
    ffi.Int Function(
        ffi.Pointer<ncplane>, ffi.Int, ffi.Int, ffi.Pointer<nccell>)>()
external int ncplane_polyfill_yx(
  ffi.Pointer<ncplane> n,
  int y,
  int x,
  ffi.Pointer<nccell> c,
);

@ffi.Native<
    ffi.Int Function(
        ffi.Pointer<ncplane>,
        ffi.Int,
        ffi.Int,
        ffi.UnsignedInt,
        ffi.UnsignedInt,
        ffi.Pointer<ffi.Char>,
        ffi.Uint16,
        ffi.Uint64,
        ffi.Uint64,
        ffi.Uint64,
        ffi.Uint64)>()
external int ncplane_gradient(
  ffi.Pointer<ncplane> n,
  int y,
  int x,
  int ylen,
  int xlen,
  ffi.Pointer<ffi.Char> egc,
  int styles,
  int ul,
  int ur,
  int ll,
  int lr,
);

@ffi.Native<
    ffi.Int Function(ffi.Pointer<ncplane>, ffi.Int, ffi.Int, ffi.UnsignedInt,
        ffi.UnsignedInt, ffi.Uint32, ffi.Uint32, ffi.Uint32, ffi.Uint32)>()
external int ncplane_gradient2x1(
  ffi.Pointer<ncplane> n,
  int y,
  int x,
  int ylen,
  int xlen,
  int ul,
  int ur,
  int ll,
  int lr,
);

@ffi.Native<
    ffi.Int Function(ffi.Pointer<ncplane>, ffi.Int, ffi.Int, ffi.UnsignedInt,
        ffi.UnsignedInt, ffi.Uint16)>()
external int ncplane_format(
  ffi.Pointer<ncplane> n,
  int y,
  int x,
  int ylen,
  int xlen,
  int stylemask,
);

@ffi.Native<
    ffi.Int Function(ffi.Pointer<ncplane>, ffi.Int, ffi.Int, ffi.UnsignedInt,
        ffi.UnsignedInt, ffi.Uint64, ffi.Uint64, ffi.Uint64, ffi.Uint64)>()
external int ncplane_stain(
  ffi.Pointer<ncplane> n,
  int y,
  int x,
  int ylen,
  int xlen,
  int ul,
  int ur,
  int ll,
  int lr,
);

@ffi.Native<ffi.Int Function(ffi.Pointer<ncplane>, ffi.Pointer<ncplane>)>()
external int ncplane_mergedown_simple(
  ffi.Pointer<ncplane> src,
  ffi.Pointer<ncplane> dst,
);

@ffi.Native<
    ffi.Int Function(ffi.Pointer<ncplane>, ffi.Pointer<ncplane>, ffi.Int,
        ffi.Int, ffi.UnsignedInt, ffi.UnsignedInt, ffi.Int, ffi.Int)>()
external int ncplane_mergedown(
  ffi.Pointer<ncplane> src,
  ffi.Pointer<ncplane> dst,
  int begsrcy,
  int begsrcx,
  int leny,
  int lenx,
  int dsty,
  int dstx,
);

@ffi.Native<ffi.Void Function(ffi.Pointer<ncplane>)>()
external void ncplane_erase(
  ffi.Pointer<ncplane> n,
);

@ffi.Native<
    ffi.Int Function(
        ffi.Pointer<ncplane>, ffi.Int, ffi.Int, ffi.Int, ffi.Int)>()
external int ncplane_erase_region(
  ffi.Pointer<ncplane> n,
  int ystart,
  int xstart,
  int ylen,
  int xlen,
);

@ffi.Native<ffi.Void Function(ffi.Pointer<ncplane>, ffi.Uint64)>()
external void ncplane_set_channels(
  ffi.Pointer<ncplane> n,
  int channels,
);

@ffi.Native<ffi.Uint64 Function(ffi.Pointer<ncplane>, ffi.Uint32)>()
external int ncplane_set_bchannel(
  ffi.Pointer<ncplane> n,
  int channel,
);

@ffi.Native<ffi.Uint64 Function(ffi.Pointer<ncplane>, ffi.Uint32)>()
external int ncplane_set_fchannel(
  ffi.Pointer<ncplane> n,
  int channel,
);

@ffi.Native<ffi.Void Function(ffi.Pointer<ncplane>, ffi.UnsignedInt)>()
external void ncplane_set_styles(
  ffi.Pointer<ncplane> n,
  int stylebits,
);

@ffi.Native<ffi.Void Function(ffi.Pointer<ncplane>, ffi.UnsignedInt)>()
external void ncplane_on_styles(
  ffi.Pointer<ncplane> n,
  int stylebits,
);

@ffi.Native<ffi.Void Function(ffi.Pointer<ncplane>, ffi.UnsignedInt)>()
external void ncplane_off_styles(
  ffi.Pointer<ncplane> n,
  int stylebits,
);

@ffi.Native<
    ffi.Int Function(ffi.Pointer<ncplane>, ffi.UnsignedInt, ffi.UnsignedInt,
        ffi.UnsignedInt)>()
external int ncplane_set_fg_rgb8(
  ffi.Pointer<ncplane> n,
  int r,
  int g,
  int b,
);

@ffi.Native<
    ffi.Int Function(ffi.Pointer<ncplane>, ffi.UnsignedInt, ffi.UnsignedInt,
        ffi.UnsignedInt)>()
external int ncplane_set_bg_rgb8(
  ffi.Pointer<ncplane> n,
  int r,
  int g,
  int b,
);

@ffi.Native<
    ffi.Void Function(ffi.Pointer<ncplane>, ffi.Int, ffi.Int, ffi.Int)>()
external void ncplane_set_bg_rgb8_clipped(
  ffi.Pointer<ncplane> n,
  int r,
  int g,
  int b,
);

@ffi.Native<
    ffi.Void Function(ffi.Pointer<ncplane>, ffi.Int, ffi.Int, ffi.Int)>()
external void ncplane_set_fg_rgb8_clipped(
  ffi.Pointer<ncplane> n,
  int r,
  int g,
  int b,
);

@ffi.Native<ffi.Int Function(ffi.Pointer<ncplane>, ffi.Uint32)>()
external int ncplane_set_fg_rgb(
  ffi.Pointer<ncplane> n,
  int channel,
);

@ffi.Native<ffi.Int Function(ffi.Pointer<ncplane>, ffi.Uint32)>()
external int ncplane_set_bg_rgb(
  ffi.Pointer<ncplane> n,
  int channel,
);

@ffi.Native<ffi.Void Function(ffi.Pointer<ncplane>)>()
external void ncplane_set_fg_default(
  ffi.Pointer<ncplane> n,
);

@ffi.Native<ffi.Void Function(ffi.Pointer<ncplane>)>()
external void ncplane_set_bg_default(
  ffi.Pointer<ncplane> n,
);

@ffi.Native<ffi.Int Function(ffi.Pointer<ncplane>, ffi.UnsignedInt)>()
external int ncplane_set_fg_palindex(
  ffi.Pointer<ncplane> n,
  int idx,
);

@ffi.Native<ffi.Int Function(ffi.Pointer<ncplane>, ffi.UnsignedInt)>()
external int ncplane_set_bg_palindex(
  ffi.Pointer<ncplane> n,
  int idx,
);

@ffi.Native<ffi.Int Function(ffi.Pointer<ncplane>, ffi.Int)>()
external int ncplane_set_fg_alpha(
  ffi.Pointer<ncplane> n,
  int alpha,
);

@ffi.Native<ffi.Int Function(ffi.Pointer<ncplane>, ffi.Int)>()
external int ncplane_set_bg_alpha(
  ffi.Pointer<ncplane> n,
  int alpha,
);

@ffi.Native<
    ffi.Int Function(ffi.Pointer<ncplane>, ffi.Pointer<timespec>, fadecb,
        ffi.Pointer<ffi.Void>)>()
external int ncplane_fadeout(
  ffi.Pointer<ncplane> n,
  ffi.Pointer<timespec> ts,
  fadecb fader,
  ffi.Pointer<ffi.Void> curry,
);

@ffi.Native<
    ffi.Int Function(ffi.Pointer<ncplane>, ffi.Pointer<timespec>, fadecb,
        ffi.Pointer<ffi.Void>)>()
external int ncplane_fadein(
  ffi.Pointer<ncplane> n,
  ffi.Pointer<timespec> ts,
  fadecb fader,
  ffi.Pointer<ffi.Void> curry,
);

@ffi.Native<ffi.Pointer<ncfadectx> Function(ffi.Pointer<ncplane>)>()
external ffi.Pointer<ncfadectx> ncfadectx_setup(
  ffi.Pointer<ncplane> n,
);

@ffi.Native<ffi.Int Function(ffi.Pointer<ncfadectx>)>()
external int ncfadectx_iterations(
  ffi.Pointer<ncfadectx> nctx,
);

@ffi.Native<
    ffi.Int Function(ffi.Pointer<ncplane>, ffi.Pointer<ncfadectx>, ffi.Int,
        fadecb, ffi.Pointer<ffi.Void>)>()
external int ncplane_fadeout_iteration(
  ffi.Pointer<ncplane> n,
  ffi.Pointer<ncfadectx> nctx,
  int iter,
  fadecb fader,
  ffi.Pointer<ffi.Void> curry,
);

@ffi.Native<
    ffi.Int Function(ffi.Pointer<ncplane>, ffi.Pointer<ncfadectx>, ffi.Int,
        fadecb, ffi.Pointer<ffi.Void>)>()
external int ncplane_fadein_iteration(
  ffi.Pointer<ncplane> n,
  ffi.Pointer<ncfadectx> nctx,
  int iter,
  fadecb fader,
  ffi.Pointer<ffi.Void> curry,
);

@ffi.Native<
    ffi.Int Function(ffi.Pointer<ncplane>, ffi.Pointer<timespec>, fadecb,
        ffi.Pointer<ffi.Void>)>()
external int ncplane_pulse(
  ffi.Pointer<ncplane> n,
  ffi.Pointer<timespec> ts,
  fadecb fader,
  ffi.Pointer<ffi.Void> curry,
);

@ffi.Native<ffi.Void Function(ffi.Pointer<ncfadectx>)>()
external void ncfadectx_free(
  ffi.Pointer<ncfadectx> nctx,
);

@ffi.Native<ffi.Pointer<ncvisual> Function(ffi.Pointer<ffi.Char>)>()
external ffi.Pointer<ncvisual> ncvisual_from_file(
  ffi.Pointer<ffi.Char> file,
);

@ffi.Native<
    ffi.Pointer<ncvisual> Function(
        ffi.Pointer<ffi.Void>, ffi.Int, ffi.Int, ffi.Int)>()
external ffi.Pointer<ncvisual> ncvisual_from_rgba(
  ffi.Pointer<ffi.Void> rgba,
  int rows,
  int rowstride,
  int cols,
);

@ffi.Native<
    ffi.Pointer<ncvisual> Function(
        ffi.Pointer<ffi.Void>, ffi.Int, ffi.Int, ffi.Int, ffi.Int)>()
external ffi.Pointer<ncvisual> ncvisual_from_rgb_packed(
  ffi.Pointer<ffi.Void> rgba,
  int rows,
  int rowstride,
  int cols,
  int alpha,
);

@ffi.Native<
    ffi.Pointer<ncvisual> Function(
        ffi.Pointer<ffi.Void>, ffi.Int, ffi.Int, ffi.Int, ffi.Int)>()
external ffi.Pointer<ncvisual> ncvisual_from_rgb_loose(
  ffi.Pointer<ffi.Void> rgba,
  int rows,
  int rowstride,
  int cols,
  int alpha,
);

@ffi.Native<
    ffi.Pointer<ncvisual> Function(
        ffi.Pointer<ffi.Void>, ffi.Int, ffi.Int, ffi.Int)>()
external ffi.Pointer<ncvisual> ncvisual_from_bgra(
  ffi.Pointer<ffi.Void> bgra,
  int rows,
  int rowstride,
  int cols,
);

@ffi.Native<
    ffi.Pointer<ncvisual> Function(ffi.Pointer<ffi.Void>, ffi.Int, ffi.Int,
        ffi.Int, ffi.Int, ffi.Int, ffi.Pointer<ffi.Uint32>)>()
external ffi.Pointer<ncvisual> ncvisual_from_palidx(
  ffi.Pointer<ffi.Void> data,
  int rows,
  int rowstride,
  int cols,
  int palsize,
  int pstride,
  ffi.Pointer<ffi.Uint32> palette,
);

@ffi.Native<
    ffi.Pointer<ncvisual> Function(ffi.Pointer<ncplane>, ffi.UnsignedInt,
        ffi.Int, ffi.Int, ffi.UnsignedInt, ffi.UnsignedInt)>()
external ffi.Pointer<ncvisual> ncvisual_from_plane(
  ffi.Pointer<ncplane> n,
  int blit,
  int begy,
  int begx,
  int leny,
  int lenx,
);

@ffi.Native<
    ffi.Pointer<ncvisual> Function(
        ffi.Pointer<ffi.Char>, ffi.UnsignedInt, ffi.UnsignedInt)>()
external ffi.Pointer<ncvisual> ncvisual_from_sixel(
  ffi.Pointer<ffi.Char> s,
  int leny,
  int lenx,
);

@ffi.Native<
    ffi.Int Function(ffi.Pointer<notcurses>, ffi.Pointer<ncvisual>,
        ffi.Pointer<ncvisual_options>, ffi.Pointer<ncvgeom>)>()
external int ncvisual_geom(
  ffi.Pointer<notcurses> nc,
  ffi.Pointer<ncvisual> n,
  ffi.Pointer<ncvisual_options> vopts,
  ffi.Pointer<ncvgeom> geom,
);

@ffi.Native<ffi.Void Function(ffi.Pointer<ncvisual>)>()
external void ncvisual_destroy(
  ffi.Pointer<ncvisual> ncv,
);

@ffi.Native<ffi.Int Function(ffi.Pointer<ncvisual>)>()
external int ncvisual_decode(
  ffi.Pointer<ncvisual> nc,
);

@ffi.Native<ffi.Int Function(ffi.Pointer<ncvisual>)>()
external int ncvisual_decode_loop(
  ffi.Pointer<ncvisual> nc,
);

@ffi.Native<ffi.Int Function(ffi.Pointer<ncvisual>, ffi.Double)>()
external int ncvisual_rotate(
  ffi.Pointer<ncvisual> n,
  double rads,
);

@ffi.Native<ffi.Int Function(ffi.Pointer<ncvisual>, ffi.Int, ffi.Int)>()
external int ncvisual_resize(
  ffi.Pointer<ncvisual> n,
  int rows,
  int cols,
);

@ffi.Native<ffi.Int Function(ffi.Pointer<ncvisual>, ffi.Int, ffi.Int)>()
external int ncvisual_resize_noninterpolative(
  ffi.Pointer<ncvisual> n,
  int rows,
  int cols,
);

@ffi.Native<
    ffi.Int Function(
        ffi.Pointer<ncvisual>, ffi.UnsignedInt, ffi.UnsignedInt, ffi.Uint32)>()
external int ncvisual_polyfill_yx(
  ffi.Pointer<ncvisual> n,
  int y,
  int x,
  int rgba,
);

@ffi.Native<
    ffi.Int Function(ffi.Pointer<ncvisual>, ffi.UnsignedInt, ffi.UnsignedInt,
        ffi.Pointer<ffi.Uint32>)>()
external int ncvisual_at_yx(
  ffi.Pointer<ncvisual> n,
  int y,
  int x,
  ffi.Pointer<ffi.Uint32> pixel,
);

@ffi.Native<
    ffi.Int Function(
        ffi.Pointer<ncvisual>, ffi.UnsignedInt, ffi.UnsignedInt, ffi.Uint32)>()
external int ncvisual_set_yx(
  ffi.Pointer<ncvisual> n,
  int y,
  int x,
  int pixel,
);

@ffi.Native<
    ffi.Pointer<ncplane> Function(ffi.Pointer<notcurses>, ffi.Pointer<ncvisual>,
        ffi.Pointer<ncvisual_options>)>()
external ffi.Pointer<ncplane> ncvisual_blit(
  ffi.Pointer<notcurses> nc,
  ffi.Pointer<ncvisual> ncv,
  ffi.Pointer<ncvisual_options> vopts,
);

@ffi.Native<
    ffi.Pointer<ncplane> Function(
        ffi.Pointer<ncplane>, ffi.Pointer<ncvisual>)>()
external ffi.Pointer<ncplane> ncvisual_subtitle_plane(
  ffi.Pointer<ncplane> parent,
  ffi.Pointer<ncvisual> ncv,
);

@ffi.Native<ffi.UnsignedInt Function(ffi.Pointer<notcurses>, ffi.UnsignedInt)>()
external int ncvisual_media_defblitter(
  ffi.Pointer<notcurses> nc,
  int scale,
);

@ffi.Native<
    ffi.Int Function(ffi.Pointer<ncvisual>, ffi.Pointer<ncvisual_options>,
        ffi.Pointer<timespec>, ffi.Pointer<ffi.Void>)>()
external int ncvisual_simple_streamer(
  ffi.Pointer<ncvisual> ncv,
  ffi.Pointer<ncvisual_options> vopts,
  ffi.Pointer<timespec> tspec,
  ffi.Pointer<ffi.Void> curry,
);

@ffi.Native<
    ffi.Int Function(ffi.Pointer<notcurses>, ffi.Pointer<ncvisual>, ffi.Float,
        ncstreamcb, ffi.Pointer<ncvisual_options>, ffi.Pointer<ffi.Void>)>()
external int ncvisual_stream(
  ffi.Pointer<notcurses> nc,
  ffi.Pointer<ncvisual> ncv,
  double timescale,
  ncstreamcb streamer,
  ffi.Pointer<ncvisual_options> vopts,
  ffi.Pointer<ffi.Void> curry,
);

@ffi.Native<
    ffi.Pointer<ncreel> Function(
        ffi.Pointer<ncplane>, ffi.Pointer<ncreel_options>)>()
external ffi.Pointer<ncreel> ncreel_create(
  ffi.Pointer<ncplane> n,
  ffi.Pointer<ncreel_options> popts,
);

@ffi.Native<ffi.Pointer<ncplane> Function(ffi.Pointer<ncreel>)>()
external ffi.Pointer<ncplane> ncreel_plane(
  ffi.Pointer<ncreel> nr,
);

@ffi.Native<
    ffi.Pointer<nctablet> Function(ffi.Pointer<ncreel>, ffi.Pointer<nctablet>,
        ffi.Pointer<nctablet>, tabletcb, ffi.Pointer<ffi.Void>)>()
external ffi.Pointer<nctablet> ncreel_add(
  ffi.Pointer<ncreel> nr,
  ffi.Pointer<nctablet> after,
  ffi.Pointer<nctablet> before,
  tabletcb cb,
  ffi.Pointer<ffi.Void> opaque,
);

@ffi.Native<ffi.Int Function(ffi.Pointer<ncreel>)>()
external int ncreel_tabletcount(
  ffi.Pointer<ncreel> nr,
);

@ffi.Native<ffi.Int Function(ffi.Pointer<ncreel>, ffi.Pointer<nctablet>)>()
external int ncreel_del(
  ffi.Pointer<ncreel> nr,
  ffi.Pointer<nctablet> t,
);

@ffi.Native<ffi.Int Function(ffi.Pointer<ncreel>)>()
external int ncreel_redraw(
  ffi.Pointer<ncreel> nr,
);

@ffi.Native<ffi.Bool Function(ffi.Pointer<ncreel>, ffi.Pointer<ncinput>)>()
external bool ncreel_offer_input(
  ffi.Pointer<ncreel> nr,
  ffi.Pointer<ncinput> ni,
);

@ffi.Native<ffi.Pointer<nctablet> Function(ffi.Pointer<ncreel>)>()
external ffi.Pointer<nctablet> ncreel_focused(
  ffi.Pointer<ncreel> nr,
);

@ffi.Native<ffi.Pointer<nctablet> Function(ffi.Pointer<ncreel>)>()
external ffi.Pointer<nctablet> ncreel_next(
  ffi.Pointer<ncreel> nr,
);

@ffi.Native<ffi.Pointer<nctablet> Function(ffi.Pointer<ncreel>)>()
external ffi.Pointer<nctablet> ncreel_prev(
  ffi.Pointer<ncreel> nr,
);

@ffi.Native<ffi.Void Function(ffi.Pointer<ncreel>)>()
external void ncreel_destroy(
  ffi.Pointer<ncreel> nr,
);

@ffi.Native<ffi.Pointer<ffi.Void> Function(ffi.Pointer<nctablet>)>()
external ffi.Pointer<ffi.Void> nctablet_userptr(
  ffi.Pointer<nctablet> t,
);

@ffi.Native<ffi.Pointer<ncplane> Function(ffi.Pointer<nctablet>)>()
external ffi.Pointer<ncplane> nctablet_plane(
  ffi.Pointer<nctablet> t,
);

@ffi.Native<ffi.Int Function(ffi.Pointer<notcurses>, ffi.Pointer<ffi.Uint32>)>()
external int notcurses_default_foreground(
  ffi.Pointer<notcurses> nc,
  ffi.Pointer<ffi.Uint32> fg,
);

@ffi.Native<ffi.Int Function(ffi.Pointer<notcurses>, ffi.Pointer<ffi.Uint32>)>()
external int notcurses_default_background(
  ffi.Pointer<notcurses> nc,
  ffi.Pointer<ffi.Uint32> bg,
);

@ffi.Native<ffi.Int Function(ffi.Pointer<notcurses>, ffi.Int, ffi.Int)>()
external int notcurses_cursor_enable(
  ffi.Pointer<notcurses> nc,
  int y,
  int x,
);

@ffi.Native<ffi.Int Function(ffi.Pointer<notcurses>)>()
external int notcurses_cursor_disable(
  ffi.Pointer<notcurses> nc,
);

@ffi.Native<
    ffi.Int Function(
        ffi.Pointer<notcurses>, ffi.Pointer<ffi.Int>, ffi.Pointer<ffi.Int>)>()
external int notcurses_cursor_yx(
  ffi.Pointer<notcurses> nc,
  ffi.Pointer<ffi.Int> y,
  ffi.Pointer<ffi.Int> x,
);

@ffi.Native<ffi.Void Function(ffi.Pointer<ncplane>)>()
external void ncplane_greyscale(
  ffi.Pointer<ncplane> n,
);

@ffi.Native<
    ffi.Pointer<ncselector> Function(
        ffi.Pointer<ncplane>, ffi.Pointer<ncselector_options>)>()
external ffi.Pointer<ncselector> ncselector_create(
  ffi.Pointer<ncplane> n,
  ffi.Pointer<ncselector_options> opts,
);

@ffi.Native<
    ffi.Int Function(ffi.Pointer<ncselector>, ffi.Pointer<ncselector_item>)>()
external int ncselector_additem(
  ffi.Pointer<ncselector> n,
  ffi.Pointer<ncselector_item> item,
);

@ffi.Native<ffi.Int Function(ffi.Pointer<ncselector>, ffi.Pointer<ffi.Char>)>()
external int ncselector_delitem(
  ffi.Pointer<ncselector> n,
  ffi.Pointer<ffi.Char> item,
);

@ffi.Native<ffi.Pointer<ffi.Char> Function(ffi.Pointer<ncselector>)>()
external ffi.Pointer<ffi.Char> ncselector_selected(
  ffi.Pointer<ncselector> n,
);

@ffi.Native<ffi.Pointer<ncplane> Function(ffi.Pointer<ncselector>)>()
external ffi.Pointer<ncplane> ncselector_plane(
  ffi.Pointer<ncselector> n,
);

@ffi.Native<ffi.Pointer<ffi.Char> Function(ffi.Pointer<ncselector>)>()
external ffi.Pointer<ffi.Char> ncselector_previtem(
  ffi.Pointer<ncselector> n,
);

@ffi.Native<ffi.Pointer<ffi.Char> Function(ffi.Pointer<ncselector>)>()
external ffi.Pointer<ffi.Char> ncselector_nextitem(
  ffi.Pointer<ncselector> n,
);

@ffi.Native<ffi.Bool Function(ffi.Pointer<ncselector>, ffi.Pointer<ncinput>)>()
external bool ncselector_offer_input(
  ffi.Pointer<ncselector> n,
  ffi.Pointer<ncinput> nc,
);

@ffi.Native<
    ffi.Void Function(
        ffi.Pointer<ncselector>, ffi.Pointer<ffi.Pointer<ffi.Char>>)>()
external void ncselector_destroy(
  ffi.Pointer<ncselector> n,
  ffi.Pointer<ffi.Pointer<ffi.Char>> item,
);

@ffi.Native<
    ffi.Pointer<ncmultiselector> Function(
        ffi.Pointer<ncplane>, ffi.Pointer<ncmultiselector_options>)>()
external ffi.Pointer<ncmultiselector> ncmultiselector_create(
  ffi.Pointer<ncplane> n,
  ffi.Pointer<ncmultiselector_options> opts,
);

@ffi.Native<
    ffi.Int Function(
        ffi.Pointer<ncmultiselector>, ffi.Pointer<ffi.Bool>, ffi.UnsignedInt)>()
external int ncmultiselector_selected(
  ffi.Pointer<ncmultiselector> n,
  ffi.Pointer<ffi.Bool> selected,
  int count,
);

@ffi.Native<ffi.Pointer<ncplane> Function(ffi.Pointer<ncmultiselector>)>()
external ffi.Pointer<ncplane> ncmultiselector_plane(
  ffi.Pointer<ncmultiselector> n,
);

@ffi.Native<
    ffi.Bool Function(ffi.Pointer<ncmultiselector>, ffi.Pointer<ncinput>)>()
external bool ncmultiselector_offer_input(
  ffi.Pointer<ncmultiselector> n,
  ffi.Pointer<ncinput> nc,
);

@ffi.Native<ffi.Void Function(ffi.Pointer<ncmultiselector>)>()
external void ncmultiselector_destroy(
  ffi.Pointer<ncmultiselector> n,
);

@ffi.Native<
    ffi.Pointer<nctree> Function(
        ffi.Pointer<ncplane>, ffi.Pointer<nctree_options>)>()
external ffi.Pointer<nctree> nctree_create(
  ffi.Pointer<ncplane> n,
  ffi.Pointer<nctree_options> opts,
);

@ffi.Native<ffi.Pointer<ncplane> Function(ffi.Pointer<nctree>)>()
external ffi.Pointer<ncplane> nctree_plane(
  ffi.Pointer<nctree> n,
);

@ffi.Native<ffi.Int Function(ffi.Pointer<nctree>)>()
external int nctree_redraw(
  ffi.Pointer<nctree> n,
);

@ffi.Native<ffi.Bool Function(ffi.Pointer<nctree>, ffi.Pointer<ncinput>)>()
external bool nctree_offer_input(
  ffi.Pointer<nctree> n,
  ffi.Pointer<ncinput> ni,
);

@ffi.Native<ffi.Pointer<ffi.Void> Function(ffi.Pointer<nctree>)>()
external ffi.Pointer<ffi.Void> nctree_focused(
  ffi.Pointer<nctree> n,
);

@ffi.Native<ffi.Pointer<ffi.Void> Function(ffi.Pointer<nctree>)>()
external ffi.Pointer<ffi.Void> nctree_next(
  ffi.Pointer<nctree> n,
);

@ffi.Native<ffi.Pointer<ffi.Void> Function(ffi.Pointer<nctree>)>()
external ffi.Pointer<ffi.Void> nctree_prev(
  ffi.Pointer<nctree> n,
);

@ffi.Native<
    ffi.Pointer<ffi.Void> Function(ffi.Pointer<nctree>,
        ffi.Pointer<ffi.UnsignedInt>, ffi.Pointer<ffi.Int>)>()
external ffi.Pointer<ffi.Void> nctree_goto(
  ffi.Pointer<nctree> n,
  ffi.Pointer<ffi.UnsignedInt> spec,
  ffi.Pointer<ffi.Int> failspec,
);

@ffi.Native<
    ffi.Int Function(ffi.Pointer<nctree>, ffi.Pointer<ffi.UnsignedInt>,
        ffi.Pointer<nctree_item>)>()
external int nctree_add(
  ffi.Pointer<nctree> n,
  ffi.Pointer<ffi.UnsignedInt> spec,
  ffi.Pointer<nctree_item> add,
);

@ffi.Native<
    ffi.Int Function(ffi.Pointer<nctree>, ffi.Pointer<ffi.UnsignedInt>)>()
external int nctree_del(
  ffi.Pointer<nctree> n,
  ffi.Pointer<ffi.UnsignedInt> spec,
);

@ffi.Native<ffi.Void Function(ffi.Pointer<nctree>)>()
external void nctree_destroy(
  ffi.Pointer<nctree> n,
);

@ffi.Native<
    ffi.Pointer<ncmenu> Function(
        ffi.Pointer<ncplane>, ffi.Pointer<ncmenu_options>)>()
external ffi.Pointer<ncmenu> ncmenu_create(
  ffi.Pointer<ncplane> n,
  ffi.Pointer<ncmenu_options> opts,
);

@ffi.Native<ffi.Int Function(ffi.Pointer<ncmenu>, ffi.Int)>()
external int ncmenu_unroll(
  ffi.Pointer<ncmenu> n,
  int sectionidx,
);

@ffi.Native<ffi.Int Function(ffi.Pointer<ncmenu>)>()
external int ncmenu_rollup(
  ffi.Pointer<ncmenu> n,
);

@ffi.Native<ffi.Int Function(ffi.Pointer<ncmenu>)>()
external int ncmenu_nextsection(
  ffi.Pointer<ncmenu> n,
);

@ffi.Native<ffi.Int Function(ffi.Pointer<ncmenu>)>()
external int ncmenu_prevsection(
  ffi.Pointer<ncmenu> n,
);

@ffi.Native<ffi.Int Function(ffi.Pointer<ncmenu>)>()
external int ncmenu_nextitem(
  ffi.Pointer<ncmenu> n,
);

@ffi.Native<ffi.Int Function(ffi.Pointer<ncmenu>)>()
external int ncmenu_previtem(
  ffi.Pointer<ncmenu> n,
);

@ffi.Native<
    ffi.Int Function(ffi.Pointer<ncmenu>, ffi.Pointer<ffi.Char>,
        ffi.Pointer<ffi.Char>, ffi.Bool)>()
external int ncmenu_item_set_status(
  ffi.Pointer<ncmenu> n,
  ffi.Pointer<ffi.Char> section,
  ffi.Pointer<ffi.Char> item,
  bool enabled,
);

@ffi.Native<
    ffi.Pointer<ffi.Char> Function(ffi.Pointer<ncmenu>, ffi.Pointer<ncinput>)>()
external ffi.Pointer<ffi.Char> ncmenu_selected(
  ffi.Pointer<ncmenu> n,
  ffi.Pointer<ncinput> ni,
);

@ffi.Native<
    ffi.Pointer<ffi.Char> Function(
        ffi.Pointer<ncmenu>, ffi.Pointer<ncinput>, ffi.Pointer<ncinput>)>()
external ffi.Pointer<ffi.Char> ncmenu_mouse_selected(
  ffi.Pointer<ncmenu> n,
  ffi.Pointer<ncinput> click,
  ffi.Pointer<ncinput> ni,
);

@ffi.Native<ffi.Pointer<ncplane> Function(ffi.Pointer<ncmenu>)>()
external ffi.Pointer<ncplane> ncmenu_plane(
  ffi.Pointer<ncmenu> n,
);

@ffi.Native<ffi.Bool Function(ffi.Pointer<ncmenu>, ffi.Pointer<ncinput>)>()
external bool ncmenu_offer_input(
  ffi.Pointer<ncmenu> n,
  ffi.Pointer<ncinput> nc,
);

@ffi.Native<ffi.Void Function(ffi.Pointer<ncmenu>)>()
external void ncmenu_destroy(
  ffi.Pointer<ncmenu> n,
);

@ffi.Native<
    ffi.Pointer<ncprogbar> Function(
        ffi.Pointer<ncplane>, ffi.Pointer<ncprogbar_options>)>()
external ffi.Pointer<ncprogbar> ncprogbar_create(
  ffi.Pointer<ncplane> n,
  ffi.Pointer<ncprogbar_options> opts,
);

@ffi.Native<ffi.Pointer<ncplane> Function(ffi.Pointer<ncprogbar>)>()
external ffi.Pointer<ncplane> ncprogbar_plane(
  ffi.Pointer<ncprogbar> n,
);

@ffi.Native<ffi.Int Function(ffi.Pointer<ncprogbar>, ffi.Double)>()
external int ncprogbar_set_progress(
  ffi.Pointer<ncprogbar> n,
  double p,
);

@ffi.Native<ffi.Double Function(ffi.Pointer<ncprogbar>)>()
external double ncprogbar_progress(
  ffi.Pointer<ncprogbar> n,
);

@ffi.Native<ffi.Void Function(ffi.Pointer<ncprogbar>)>()
external void ncprogbar_destroy(
  ffi.Pointer<ncprogbar> n,
);

@ffi.Native<
    ffi.Pointer<nctabbed> Function(
        ffi.Pointer<ncplane>, ffi.Pointer<nctabbed_options>)>()
external ffi.Pointer<nctabbed> nctabbed_create(
  ffi.Pointer<ncplane> n,
  ffi.Pointer<nctabbed_options> opts,
);

@ffi.Native<ffi.Void Function(ffi.Pointer<nctabbed>)>()
external void nctabbed_destroy(
  ffi.Pointer<nctabbed> nt,
);

@ffi.Native<ffi.Void Function(ffi.Pointer<nctabbed>)>()
external void nctabbed_redraw(
  ffi.Pointer<nctabbed> nt,
);

@ffi.Native<ffi.Void Function(ffi.Pointer<nctabbed>)>()
external void nctabbed_ensure_selected_header_visible(
  ffi.Pointer<nctabbed> nt,
);

@ffi.Native<ffi.Pointer<nctab> Function(ffi.Pointer<nctabbed>)>()
external ffi.Pointer<nctab> nctabbed_selected(
  ffi.Pointer<nctabbed> nt,
);

@ffi.Native<ffi.Pointer<nctab> Function(ffi.Pointer<nctabbed>)>()
external ffi.Pointer<nctab> nctabbed_leftmost(
  ffi.Pointer<nctabbed> nt,
);

@ffi.Native<ffi.Int Function(ffi.Pointer<nctabbed>)>()
external int nctabbed_tabcount(
  ffi.Pointer<nctabbed> nt,
);

@ffi.Native<ffi.Pointer<ncplane> Function(ffi.Pointer<nctabbed>)>()
external ffi.Pointer<ncplane> nctabbed_plane(
  ffi.Pointer<nctabbed> nt,
);

@ffi.Native<ffi.Pointer<ncplane> Function(ffi.Pointer<nctabbed>)>()
external ffi.Pointer<ncplane> nctabbed_content_plane(
  ffi.Pointer<nctabbed> nt,
);

@ffi.Native<tabcb Function(ffi.Pointer<nctab>)>()
external tabcb nctab_cb(
  ffi.Pointer<nctab> t,
);

@ffi.Native<ffi.Pointer<ffi.Char> Function(ffi.Pointer<nctab>)>()
external ffi.Pointer<ffi.Char> nctab_name(
  ffi.Pointer<nctab> t,
);

@ffi.Native<ffi.Int Function(ffi.Pointer<nctab>)>()
external int nctab_name_width(
  ffi.Pointer<nctab> t,
);

@ffi.Native<ffi.Pointer<ffi.Void> Function(ffi.Pointer<nctab>)>()
external ffi.Pointer<ffi.Void> nctab_userptr(
  ffi.Pointer<nctab> t,
);

@ffi.Native<ffi.Pointer<nctab> Function(ffi.Pointer<nctab>)>()
external ffi.Pointer<nctab> nctab_next(
  ffi.Pointer<nctab> t,
);

@ffi.Native<ffi.Pointer<nctab> Function(ffi.Pointer<nctab>)>()
external ffi.Pointer<nctab> nctab_prev(
  ffi.Pointer<nctab> t,
);

@ffi.Native<
    ffi.Pointer<nctab> Function(
        ffi.Pointer<nctabbed>,
        ffi.Pointer<nctab>,
        ffi.Pointer<nctab>,
        tabcb,
        ffi.Pointer<ffi.Char>,
        ffi.Pointer<ffi.Void>)>()
external ffi.Pointer<nctab> nctabbed_add(
  ffi.Pointer<nctabbed> nt,
  ffi.Pointer<nctab> after,
  ffi.Pointer<nctab> before,
  tabcb tcb,
  ffi.Pointer<ffi.Char> name,
  ffi.Pointer<ffi.Void> opaque,
);

@ffi.Native<ffi.Int Function(ffi.Pointer<nctabbed>, ffi.Pointer<nctab>)>()
external int nctabbed_del(
  ffi.Pointer<nctabbed> nt,
  ffi.Pointer<nctab> t,
);

@ffi.Native<
    ffi.Int Function(ffi.Pointer<nctabbed>, ffi.Pointer<nctab>,
        ffi.Pointer<nctab>, ffi.Pointer<nctab>)>()
external int nctab_move(
  ffi.Pointer<nctabbed> nt,
  ffi.Pointer<nctab> t,
  ffi.Pointer<nctab> after,
  ffi.Pointer<nctab> before,
);

@ffi.Native<ffi.Void Function(ffi.Pointer<nctabbed>, ffi.Pointer<nctab>)>()
external void nctab_move_right(
  ffi.Pointer<nctabbed> nt,
  ffi.Pointer<nctab> t,
);

@ffi.Native<ffi.Void Function(ffi.Pointer<nctabbed>, ffi.Pointer<nctab>)>()
external void nctab_move_left(
  ffi.Pointer<nctabbed> nt,
  ffi.Pointer<nctab> t,
);

@ffi.Native<ffi.Void Function(ffi.Pointer<nctabbed>, ffi.Int)>()
external void nctabbed_rotate(
  ffi.Pointer<nctabbed> nt,
  int amt,
);

@ffi.Native<ffi.Pointer<nctab> Function(ffi.Pointer<nctabbed>)>()
external ffi.Pointer<nctab> nctabbed_next(
  ffi.Pointer<nctabbed> nt,
);

@ffi.Native<ffi.Pointer<nctab> Function(ffi.Pointer<nctabbed>)>()
external ffi.Pointer<nctab> nctabbed_prev(
  ffi.Pointer<nctabbed> nt,
);

@ffi.Native<
    ffi.Pointer<nctab> Function(ffi.Pointer<nctabbed>, ffi.Pointer<nctab>)>()
external ffi.Pointer<nctab> nctabbed_select(
  ffi.Pointer<nctabbed> nt,
  ffi.Pointer<nctab> t,
);

@ffi.Native<
    ffi.Void Function(ffi.Pointer<nctabbed>, ffi.Pointer<ffi.Uint64>,
        ffi.Pointer<ffi.Uint64>, ffi.Pointer<ffi.Uint64>)>()
external void nctabbed_channels(
  ffi.Pointer<nctabbed> nt,
  ffi.Pointer<ffi.Uint64> hdrchan,
  ffi.Pointer<ffi.Uint64> selchan,
  ffi.Pointer<ffi.Uint64> sepchan,
);

@ffi.Native<ffi.Pointer<ffi.Char> Function(ffi.Pointer<nctabbed>)>()
external ffi.Pointer<ffi.Char> nctabbed_separator(
  ffi.Pointer<nctabbed> nt,
);

@ffi.Native<ffi.Int Function(ffi.Pointer<nctabbed>)>()
external int nctabbed_separator_width(
  ffi.Pointer<nctabbed> nt,
);

@ffi.Native<ffi.Void Function(ffi.Pointer<nctabbed>, ffi.Uint64)>()
external void nctabbed_set_hdrchan(
  ffi.Pointer<nctabbed> nt,
  int chan,
);

@ffi.Native<ffi.Void Function(ffi.Pointer<nctabbed>, ffi.Uint64)>()
external void nctabbed_set_selchan(
  ffi.Pointer<nctabbed> nt,
  int chan,
);

@ffi.Native<ffi.Void Function(ffi.Pointer<nctabbed>, ffi.Uint64)>()
external void nctabbed_set_sepchan(
  ffi.Pointer<nctabbed> nt,
  int chan,
);

@ffi.Native<tabcb Function(ffi.Pointer<nctab>, tabcb)>()
external tabcb nctab_set_cb(
  ffi.Pointer<nctab> t,
  tabcb newcb,
);

@ffi.Native<ffi.Int Function(ffi.Pointer<nctab>, ffi.Pointer<ffi.Char>)>()
external int nctab_set_name(
  ffi.Pointer<nctab> t,
  ffi.Pointer<ffi.Char> newname,
);

@ffi.Native<
    ffi.Pointer<ffi.Void> Function(ffi.Pointer<nctab>, ffi.Pointer<ffi.Void>)>()
external ffi.Pointer<ffi.Void> nctab_set_userptr(
  ffi.Pointer<nctab> t,
  ffi.Pointer<ffi.Void> newopaque,
);

@ffi.Native<ffi.Int Function(ffi.Pointer<nctabbed>, ffi.Pointer<ffi.Char>)>()
external int nctabbed_set_separator(
  ffi.Pointer<nctabbed> nt,
  ffi.Pointer<ffi.Char> separator,
);

@ffi.Native<
    ffi.Pointer<ncuplot> Function(ffi.Pointer<ncplane>,
        ffi.Pointer<ncplot_options>, ffi.Uint64, ffi.Uint64)>()
external ffi.Pointer<ncuplot> ncuplot_create(
  ffi.Pointer<ncplane> n,
  ffi.Pointer<ncplot_options> opts,
  int miny,
  int maxy,
);

@ffi.Native<ffi.Pointer<ncplane> Function(ffi.Pointer<ncuplot>)>()
external ffi.Pointer<ncplane> ncuplot_plane(
  ffi.Pointer<ncuplot> n,
);

@ffi.Native<ffi.Int Function(ffi.Pointer<ncuplot>, ffi.Uint64, ffi.Uint64)>()
external int ncuplot_add_sample(
  ffi.Pointer<ncuplot> n,
  int x,
  int y,
);

@ffi.Native<ffi.Int Function(ffi.Pointer<ncuplot>, ffi.Uint64, ffi.Uint64)>()
external int ncuplot_set_sample(
  ffi.Pointer<ncuplot> n,
  int x,
  int y,
);

@ffi.Native<
    ffi.Int Function(
        ffi.Pointer<ncuplot>, ffi.Uint64, ffi.Pointer<ffi.Uint64>)>()
external int ncuplot_sample(
  ffi.Pointer<ncuplot> n,
  int x,
  ffi.Pointer<ffi.Uint64> y,
);

@ffi.Native<ffi.Void Function(ffi.Pointer<ncuplot>)>()
external void ncuplot_destroy(
  ffi.Pointer<ncuplot> n,
);

@ffi.Native<
    ffi.Pointer<ncfdplane> Function(
        ffi.Pointer<ncplane>,
        ffi.Pointer<ncfdplane_options>,
        ffi.Int,
        ncfdplane_callback,
        ncfdplane_done_cb)>()
external ffi.Pointer<ncfdplane> ncfdplane_create(
  ffi.Pointer<ncplane> n,
  ffi.Pointer<ncfdplane_options> opts,
  int fd,
  ncfdplane_callback cbfxn,
  ncfdplane_done_cb donecbfxn,
);

@ffi.Native<ffi.Pointer<ncplane> Function(ffi.Pointer<ncfdplane>)>()
external ffi.Pointer<ncplane> ncfdplane_plane(
  ffi.Pointer<ncfdplane> n,
);

@ffi.Native<ffi.Int Function(ffi.Pointer<ncfdplane>)>()
external int ncfdplane_destroy(
  ffi.Pointer<ncfdplane> n,
);

@ffi.Native<
    ffi.Pointer<ncsubproc> Function(
        ffi.Pointer<ncplane>,
        ffi.Pointer<ncsubproc_options>,
        ffi.Pointer<ffi.Char>,
        ffi.Pointer<ffi.Pointer<ffi.Char>>,
        ncfdplane_callback,
        ncfdplane_done_cb)>()
external ffi.Pointer<ncsubproc> ncsubproc_createv(
  ffi.Pointer<ncplane> n,
  ffi.Pointer<ncsubproc_options> opts,
  ffi.Pointer<ffi.Char> bin,
  ffi.Pointer<ffi.Pointer<ffi.Char>> arg,
  ncfdplane_callback cbfxn,
  ncfdplane_done_cb donecbfxn,
);

@ffi.Native<
    ffi.Pointer<ncsubproc> Function(
        ffi.Pointer<ncplane>,
        ffi.Pointer<ncsubproc_options>,
        ffi.Pointer<ffi.Char>,
        ffi.Pointer<ffi.Pointer<ffi.Char>>,
        ncfdplane_callback,
        ncfdplane_done_cb)>()
external ffi.Pointer<ncsubproc> ncsubproc_createvp(
  ffi.Pointer<ncplane> n,
  ffi.Pointer<ncsubproc_options> opts,
  ffi.Pointer<ffi.Char> bin,
  ffi.Pointer<ffi.Pointer<ffi.Char>> arg,
  ncfdplane_callback cbfxn,
  ncfdplane_done_cb donecbfxn,
);

@ffi.Native<
    ffi.Pointer<ncsubproc> Function(
        ffi.Pointer<ncplane>,
        ffi.Pointer<ncsubproc_options>,
        ffi.Pointer<ffi.Char>,
        ffi.Pointer<ffi.Pointer<ffi.Char>>,
        ffi.Pointer<ffi.Pointer<ffi.Char>>,
        ncfdplane_callback,
        ncfdplane_done_cb)>()
external ffi.Pointer<ncsubproc> ncsubproc_createvpe(
  ffi.Pointer<ncplane> n,
  ffi.Pointer<ncsubproc_options> opts,
  ffi.Pointer<ffi.Char> bin,
  ffi.Pointer<ffi.Pointer<ffi.Char>> arg,
  ffi.Pointer<ffi.Pointer<ffi.Char>> env,
  ncfdplane_callback cbfxn,
  ncfdplane_done_cb donecbfxn,
);

@ffi.Native<ffi.Pointer<ncplane> Function(ffi.Pointer<ncsubproc>)>()
external ffi.Pointer<ncplane> ncsubproc_plane(
  ffi.Pointer<ncsubproc> n,
);

@ffi.Native<ffi.Int Function(ffi.Pointer<ncsubproc>)>()
external int ncsubproc_destroy(
  ffi.Pointer<ncsubproc> n,
);

@ffi.Native<
    ffi.Int Function(ffi.Pointer<ncplane>, ffi.Pointer<ffi.UnsignedInt>,
        ffi.Pointer<ffi.UnsignedInt>, ffi.Pointer<ffi.Void>, ffi.Size)>()
external int ncplane_qrcode(
  ffi.Pointer<ncplane> n,
  ffi.Pointer<ffi.UnsignedInt> ymax,
  ffi.Pointer<ffi.UnsignedInt> xmax,
  ffi.Pointer<ffi.Void> data,
  int len,
);

@ffi.Native<
    ffi.Pointer<ncreader> Function(
        ffi.Pointer<ncplane>, ffi.Pointer<ncreader_options>)>()
external ffi.Pointer<ncreader> ncreader_create(
  ffi.Pointer<ncplane> n,
  ffi.Pointer<ncreader_options> opts,
);

@ffi.Native<ffi.Int Function(ffi.Pointer<ncreader>)>()
external int ncreader_clear(
  ffi.Pointer<ncreader> n,
);

@ffi.Native<ffi.Pointer<ncplane> Function(ffi.Pointer<ncreader>)>()
external ffi.Pointer<ncplane> ncreader_plane(
  ffi.Pointer<ncreader> n,
);

@ffi.Native<ffi.Bool Function(ffi.Pointer<ncreader>, ffi.Pointer<ncinput>)>()
external bool ncreader_offer_input(
  ffi.Pointer<ncreader> n,
  ffi.Pointer<ncinput> ni,
);

@ffi.Native<ffi.Int Function(ffi.Pointer<ncreader>)>()
external int ncreader_move_left(
  ffi.Pointer<ncreader> n,
);

@ffi.Native<ffi.Int Function(ffi.Pointer<ncreader>)>()
external int ncreader_move_right(
  ffi.Pointer<ncreader> n,
);

@ffi.Native<ffi.Int Function(ffi.Pointer<ncreader>)>()
external int ncreader_move_up(
  ffi.Pointer<ncreader> n,
);

@ffi.Native<ffi.Int Function(ffi.Pointer<ncreader>)>()
external int ncreader_move_down(
  ffi.Pointer<ncreader> n,
);

@ffi.Native<ffi.Int Function(ffi.Pointer<ncreader>, ffi.Pointer<ffi.Char>)>()
external int ncreader_write_egc(
  ffi.Pointer<ncreader> n,
  ffi.Pointer<ffi.Char> egc,
);

@ffi.Native<ffi.Pointer<ffi.Char> Function(ffi.Pointer<ncreader>)>()
external ffi.Pointer<ffi.Char> ncreader_contents(
  ffi.Pointer<ncreader> n,
);

@ffi.Native<
    ffi.Void Function(
        ffi.Pointer<ncreader>, ffi.Pointer<ffi.Pointer<ffi.Char>>)>()
external void ncreader_destroy(
  ffi.Pointer<ncreader> n,
  ffi.Pointer<ffi.Pointer<ffi.Char>> contents,
);

@ffi.Native<ffi.Pointer<ffi.Char> Function()>()
external ffi.Pointer<ffi.Char> notcurses_accountname();

@ffi.Native<ffi.Pointer<ffi.Char> Function()>()
external ffi.Pointer<ffi.Char> notcurses_hostname();

@ffi.Native<ffi.Pointer<ffi.Char> Function()>()
external ffi.Pointer<ffi.Char> notcurses_osversion();

@ffi.Native<ffi.Void Function(ffi.Pointer<notcurses>, ffi.Pointer<FILE>)>()
external void notcurses_debug(
  ffi.Pointer<notcurses> nc,
  ffi.Pointer<FILE> debugfp,
);

@ffi.Native<
    ffi.Pointer<ncdirect> Function(
        ffi.Pointer<ffi.Char>, ffi.Pointer<FILE>, ffi.Uint64)>()
external ffi.Pointer<ncdirect> ncdirect_init(
  ffi.Pointer<ffi.Char> termtype,
  ffi.Pointer<FILE> fp,
  int flags,
);

@ffi.Native<
    ffi.Pointer<ncdirect> Function(
        ffi.Pointer<ffi.Char>, ffi.Pointer<FILE>, ffi.Uint64)>()
external ffi.Pointer<ncdirect> ncdirect_core_init(
  ffi.Pointer<ffi.Char> termtype,
  ffi.Pointer<FILE> fp,
  int flags,
);

@ffi.Native<
    ffi.Pointer<ffi.Char> Function(
        ffi.Pointer<ncdirect>, ffi.Pointer<ffi.Char>)>()
external ffi.Pointer<ffi.Char> ncdirect_readline(
  ffi.Pointer<ncdirect> nc,
  ffi.Pointer<ffi.Char> prompt,
);

@ffi.Native<ffi.Int Function(ffi.Pointer<ncdirect>, ffi.UnsignedInt)>()
external int ncdirect_set_fg_rgb(
  ffi.Pointer<ncdirect> nc,
  int rgb,
);

@ffi.Native<ffi.Int Function(ffi.Pointer<ncdirect>, ffi.UnsignedInt)>()
external int ncdirect_set_bg_rgb(
  ffi.Pointer<ncdirect> nc,
  int rgb,
);

@ffi.Native<ffi.Int Function(ffi.Pointer<ncdirect>, ffi.Int)>()
external int ncdirect_set_fg_palindex(
  ffi.Pointer<ncdirect> nc,
  int pidx,
);

@ffi.Native<ffi.Int Function(ffi.Pointer<ncdirect>, ffi.Int)>()
external int ncdirect_set_bg_palindex(
  ffi.Pointer<ncdirect> nc,
  int pidx,
);

@ffi.Native<ffi.UnsignedInt Function(ffi.Pointer<ncdirect>)>()
external int ncdirect_palette_size(
  ffi.Pointer<ncdirect> nc,
);

@ffi.Native<
    ffi.Int Function(
        ffi.Pointer<ncdirect>, ffi.Uint64, ffi.Pointer<ffi.Char>)>()
external int ncdirect_putstr(
  ffi.Pointer<ncdirect> nc,
  int channels,
  ffi.Pointer<ffi.Char> utf8,
);

@ffi.Native<
    ffi.Int Function(ffi.Pointer<ncdirect>, ffi.Uint64, ffi.Pointer<ffi.Char>,
        ffi.Pointer<ffi.Int>)>()
external int ncdirect_putegc(
  ffi.Pointer<ncdirect> nc,
  int channels,
  ffi.Pointer<ffi.Char> utf8,
  ffi.Pointer<ffi.Int> sbytes,
);

@ffi.Native<
    ffi.Int Function(ffi.Pointer<ncdirect>, ffi.Int, ffi.UnsignedInt,
        ffi.Pointer<ffi.Char>)>()
external int ncdirect_printf_aligned(
  ffi.Pointer<ncdirect> n,
  int y,
  int align,
  ffi.Pointer<ffi.Char> fmt,
);

@ffi.Native<ffi.Int Function(ffi.Pointer<ncdirect>)>()
external int ncdirect_flush(
  ffi.Pointer<ncdirect> nc,
);

@ffi.Native<ffi.Int Function(ffi.Pointer<ncdirect>)>()
external int ncdirect_set_fg_default(
  ffi.Pointer<ncdirect> nc,
);

@ffi.Native<ffi.Int Function(ffi.Pointer<ncdirect>)>()
external int ncdirect_set_bg_default(
  ffi.Pointer<ncdirect> nc,
);

@ffi.Native<ffi.UnsignedInt Function(ffi.Pointer<ncdirect>)>()
external int ncdirect_dim_x(
  ffi.Pointer<ncdirect> nc,
);

@ffi.Native<ffi.UnsignedInt Function(ffi.Pointer<ncdirect>)>()
external int ncdirect_dim_y(
  ffi.Pointer<ncdirect> nc,
);

@ffi.Native<ffi.Uint16 Function(ffi.Pointer<ncdirect>)>()
external int ncdirect_supported_styles(
  ffi.Pointer<ncdirect> nc,
);

@ffi.Native<ffi.Int Function(ffi.Pointer<ncdirect>, ffi.UnsignedInt)>()
external int ncdirect_set_styles(
  ffi.Pointer<ncdirect> n,
  int stylebits,
);

@ffi.Native<ffi.Int Function(ffi.Pointer<ncdirect>, ffi.UnsignedInt)>()
external int ncdirect_on_styles(
  ffi.Pointer<ncdirect> n,
  int stylebits,
);

@ffi.Native<ffi.Int Function(ffi.Pointer<ncdirect>, ffi.UnsignedInt)>()
external int ncdirect_off_styles(
  ffi.Pointer<ncdirect> n,
  int stylebits,
);

@ffi.Native<ffi.Uint16 Function(ffi.Pointer<ncdirect>)>()
external int ncdirect_styles(
  ffi.Pointer<ncdirect> n,
);

@ffi.Native<ffi.Int Function(ffi.Pointer<ncdirect>, ffi.Int, ffi.Int)>()
external int ncdirect_cursor_move_yx(
  ffi.Pointer<ncdirect> n,
  int y,
  int x,
);

@ffi.Native<ffi.Int Function(ffi.Pointer<ncdirect>)>()
external int ncdirect_cursor_enable(
  ffi.Pointer<ncdirect> nc,
);

@ffi.Native<ffi.Int Function(ffi.Pointer<ncdirect>)>()
external int ncdirect_cursor_disable(
  ffi.Pointer<ncdirect> nc,
);

@ffi.Native<ffi.Int Function(ffi.Pointer<ncdirect>, ffi.Int)>()
external int ncdirect_cursor_up(
  ffi.Pointer<ncdirect> nc,
  int num,
);

@ffi.Native<ffi.Int Function(ffi.Pointer<ncdirect>, ffi.Int)>()
external int ncdirect_cursor_left(
  ffi.Pointer<ncdirect> nc,
  int num,
);

@ffi.Native<ffi.Int Function(ffi.Pointer<ncdirect>, ffi.Int)>()
external int ncdirect_cursor_right(
  ffi.Pointer<ncdirect> nc,
  int num,
);

@ffi.Native<ffi.Int Function(ffi.Pointer<ncdirect>, ffi.Int)>()
external int ncdirect_cursor_down(
  ffi.Pointer<ncdirect> nc,
  int num,
);

@ffi.Native<
    ffi.Int Function(ffi.Pointer<ncdirect>, ffi.Pointer<ffi.UnsignedInt>,
        ffi.Pointer<ffi.UnsignedInt>)>()
external int ncdirect_cursor_yx(
  ffi.Pointer<ncdirect> n,
  ffi.Pointer<ffi.UnsignedInt> y,
  ffi.Pointer<ffi.UnsignedInt> x,
);

@ffi.Native<ffi.Int Function(ffi.Pointer<ncdirect>)>()
external int ncdirect_cursor_push(
  ffi.Pointer<ncdirect> n,
);

@ffi.Native<ffi.Int Function(ffi.Pointer<ncdirect>)>()
external int ncdirect_cursor_pop(
  ffi.Pointer<ncdirect> n,
);

@ffi.Native<ffi.Int Function(ffi.Pointer<ncdirect>)>()
external int ncdirect_clear(
  ffi.Pointer<ncdirect> nc,
);

@ffi.Native<ffi.Pointer<nccapabilities> Function(ffi.Pointer<ncdirect>)>()
external ffi.Pointer<nccapabilities> ncdirect_capabilities(
  ffi.Pointer<ncdirect> n,
);

@ffi.Native<
    ffi.Int Function(ffi.Pointer<ncdirect>, ffi.Pointer<ffi.Char>,
        ffi.UnsignedInt, ffi.Uint64, ffi.Uint64)>()
external int ncdirect_hline_interp(
  ffi.Pointer<ncdirect> n,
  ffi.Pointer<ffi.Char> egc,
  int len,
  int h1,
  int h2,
);

@ffi.Native<
    ffi.Int Function(ffi.Pointer<ncdirect>, ffi.Pointer<ffi.Char>,
        ffi.UnsignedInt, ffi.Uint64, ffi.Uint64)>()
external int ncdirect_vline_interp(
  ffi.Pointer<ncdirect> n,
  ffi.Pointer<ffi.Char> egc,
  int len,
  int h1,
  int h2,
);

@ffi.Native<
    ffi.Int Function(
        ffi.Pointer<ncdirect>,
        ffi.Uint64,
        ffi.Uint64,
        ffi.Uint64,
        ffi.Uint64,
        ffi.Pointer<ffi.WChar>,
        ffi.UnsignedInt,
        ffi.UnsignedInt,
        ffi.UnsignedInt)>()
external int ncdirect_box(
  ffi.Pointer<ncdirect> n,
  int ul,
  int ur,
  int ll,
  int lr,
  ffi.Pointer<ffi.WChar> wchars,
  int ylen,
  int xlen,
  int ctlword,
);

@ffi.Native<
    ffi.Int Function(ffi.Pointer<ncdirect>, ffi.Uint64, ffi.Uint64, ffi.Uint64,
        ffi.Uint64, ffi.UnsignedInt, ffi.UnsignedInt, ffi.UnsignedInt)>()
external int ncdirect_rounded_box(
  ffi.Pointer<ncdirect> n,
  int ul,
  int ur,
  int ll,
  int lr,
  int ylen,
  int xlen,
  int ctlword,
);

@ffi.Native<
    ffi.Int Function(ffi.Pointer<ncdirect>, ffi.Uint64, ffi.Uint64, ffi.Uint64,
        ffi.Uint64, ffi.UnsignedInt, ffi.UnsignedInt, ffi.UnsignedInt)>()
external int ncdirect_double_box(
  ffi.Pointer<ncdirect> n,
  int ul,
  int ur,
  int ll,
  int lr,
  int ylen,
  int xlen,
  int ctlword,
);

@ffi.Native<
    ffi.Uint32 Function(
        ffi.Pointer<ncdirect>, ffi.Pointer<timespec>, ffi.Pointer<ncinput>)>()
external int ncdirect_get(
  ffi.Pointer<ncdirect> n,
  ffi.Pointer<timespec> absdl,
  ffi.Pointer<ncinput> ni,
);

@ffi.Native<ffi.Int Function(ffi.Pointer<ncdirect>)>()
external int ncdirect_inputready_fd(
  ffi.Pointer<ncdirect> n,
);

@ffi.Native<ffi.Int Function(ffi.Pointer<ncdirect>)>()
external int ncdirect_stop(
  ffi.Pointer<ncdirect> nc,
);

@ffi.Native<
    ffi.Int Function(ffi.Pointer<ncdirect>, ffi.Pointer<ffi.Char>,
        ffi.UnsignedInt, ffi.UnsignedInt, ffi.UnsignedInt)>()
external int ncdirect_render_image(
  ffi.Pointer<ncdirect> n,
  ffi.Pointer<ffi.Char> filename,
  int align,
  int blitter,
  int scale,
);

@ffi.Native<
    ffi.Pointer<ncdirectv> Function(
        ffi.Pointer<ncdirect>,
        ffi.Pointer<ffi.Char>,
        ffi.UnsignedInt,
        ffi.UnsignedInt,
        ffi.Int,
        ffi.Int)>()
external ffi.Pointer<ncdirectv> ncdirect_render_frame(
  ffi.Pointer<ncdirect> n,
  ffi.Pointer<ffi.Char> filename,
  int blitter,
  int scale,
  int maxy,
  int maxx,
);

@ffi.Native<
    ffi.Int Function(
        ffi.Pointer<ncdirect>, ffi.Pointer<ncdirectv>, ffi.UnsignedInt)>()
external int ncdirect_raster_frame(
  ffi.Pointer<ncdirect> n,
  ffi.Pointer<ncdirectv> ncdv,
  int align,
);

@ffi.Native<
    ffi.Pointer<ncdirectf> Function(
        ffi.Pointer<ncdirect>, ffi.Pointer<ffi.Char>)>()
external ffi.Pointer<ncdirectf> ncdirectf_from_file(
  ffi.Pointer<ncdirect> n,
  ffi.Pointer<ffi.Char> filename,
);

@ffi.Native<ffi.Void Function(ffi.Pointer<ncdirectf>)>()
external void ncdirectf_free(
  ffi.Pointer<ncdirectf> frame,
);

@ffi.Native<
    ffi.Pointer<ncdirectv> Function(ffi.Pointer<ncdirect>,
        ffi.Pointer<ncdirectf>, ffi.Pointer<ncvisual_options>)>()
external ffi.Pointer<ncdirectv> ncdirectf_render(
  ffi.Pointer<ncdirect> n,
  ffi.Pointer<ncdirectf> frame,
  ffi.Pointer<ncvisual_options> vopts,
);

@ffi.Native<
    ffi.Int Function(ffi.Pointer<ncdirect>, ffi.Pointer<ncdirectf>,
        ffi.Pointer<ncvisual_options>, ffi.Pointer<ncvgeom>)>()
external int ncdirectf_geom(
  ffi.Pointer<ncdirect> n,
  ffi.Pointer<ncdirectf> frame,
  ffi.Pointer<ncvisual_options> vopts,
  ffi.Pointer<ncvgeom> geom,
);

@ffi.Native<
    ffi.Int Function(ffi.Pointer<ncdirect>, ffi.Pointer<ffi.Char>, ncstreamcb,
        ffi.Pointer<ncvisual_options>, ffi.Pointer<ffi.Void>)>()
external int ncdirect_stream(
  ffi.Pointer<ncdirect> n,
  ffi.Pointer<ffi.Char> filename,
  ncstreamcb streamer,
  ffi.Pointer<ncvisual_options> vopts,
  ffi.Pointer<ffi.Void> curry,
);

@ffi.Native<ffi.Pointer<ffi.Char> Function(ffi.Pointer<ncdirect>)>()
external ffi.Pointer<ffi.Char> ncdirect_detected_terminal(
  ffi.Pointer<ncdirect> n,
);

@ffi.Native<ffi.Bool Function(ffi.Pointer<ncdirect>)>()
external bool ncdirect_canutf8(
  ffi.Pointer<ncdirect> n,
);

@ffi.Native<ffi.Int Function(ffi.Pointer<ncdirect>)>()
external int ncdirect_check_pixel_support(
  ffi.Pointer<ncdirect> n,
);

@ffi.Native<ffi.Bool Function(ffi.Pointer<ncdirect>)>()
external bool ncdirect_canget_cursor(
  ffi.Pointer<ncdirect> nc,
);

final class notcurses extends ffi.Opaque {}

final class ncplane extends ffi.Opaque {}

final class ncvisual extends ffi.Opaque {}

final class ncuplot extends ffi.Opaque {}

final class ncdplot extends ffi.Opaque {}

final class ncprogbar extends ffi.Opaque {}

final class ncfdplane extends ffi.Opaque {}

final class ncsubproc extends ffi.Opaque {}

final class ncselector extends ffi.Opaque {}

final class ncmultiselector extends ffi.Opaque {}

final class ncreader extends ffi.Opaque {}

final class ncfadectx extends ffi.Opaque {}

final class nctablet extends ffi.Opaque {}

final class ncreel extends ffi.Opaque {}

final class nctab extends ffi.Opaque {}

final class nctabbed extends ffi.Opaque {}

final class ncdirect extends ffi.Opaque {}

sealed class ncblitter_e {
  static const NCBLIT_DEFAULT = 0;
  static const NCBLIT_1x1 = 1;
  static const NCBLIT_2x1 = 2;
  static const NCBLIT_2x2 = 3;
  static const NCBLIT_3x2 = 4;
  static const NCBLIT_4x2 = 5;
  static const NCBLIT_BRAILLE = 6;
  static const NCBLIT_PIXEL = 7;
  static const NCBLIT_4x1 = 8;
  static const NCBLIT_8x1 = 9;
}

sealed class ncalign_e {
  static const NCALIGN_UNALIGNED = 0;
  static const NCALIGN_LEFT = 1;
  static const NCALIGN_CENTER = 2;
  static const NCALIGN_RIGHT = 3;
}

sealed class ncscale_e {
  static const NCSCALE_NONE = 0;
  static const NCSCALE_SCALE = 1;
  static const NCSCALE_STRETCH = 2;
  static const NCSCALE_NONE_HIRES = 3;
  static const NCSCALE_SCALE_HIRES = 4;
}

final class nccell extends ffi.Struct {
  @ffi.Uint32()
  external int gcluster;

  @ffi.Uint8()
  external int gcluster_backstop;

  @ffi.Uint8()
  external int width;

  @ffi.Uint16()
  external int stylemask;

  @ffi.Uint64()
  external int channels;
}

sealed class ncloglevel_e {
  static const NCLOGLEVEL_SILENT = -1;
  static const NCLOGLEVEL_PANIC = 0;
  static const NCLOGLEVEL_FATAL = 1;
  static const NCLOGLEVEL_ERROR = 2;
  static const NCLOGLEVEL_WARNING = 3;
  static const NCLOGLEVEL_INFO = 4;
  static const NCLOGLEVEL_VERBOSE = 5;
  static const NCLOGLEVEL_DEBUG = 6;
  static const NCLOGLEVEL_TRACE = 7;
}

final class notcurses_options extends ffi.Struct {
  external ffi.Pointer<ffi.Char> termtype;

  @ffi.Int()
  external int loglevel;

  @ffi.UnsignedInt()
  external int margin_t;

  @ffi.UnsignedInt()
  external int margin_r;

  @ffi.UnsignedInt()
  external int margin_b;

  @ffi.UnsignedInt()
  external int margin_l;

  @ffi.Uint64()
  external int flags;
}

final class __sbuf extends ffi.Struct {
  external ffi.Pointer<ffi.UnsignedChar> _base;

  @ffi.Int()
  external int _size;
}

typedef fpos_t = ffi.LongLong;

final class __sFILEX extends ffi.Opaque {}

final class __sFILE extends ffi.Struct {
  external ffi.Pointer<ffi.UnsignedChar> _p;

  @ffi.Int()
  external int _r;

  @ffi.Int()
  external int _w;

  @ffi.Short()
  external int _flags;

  @ffi.Short()
  external int _file;

  external __sbuf _bf;

  @ffi.Int()
  external int _lbfsize;

  external ffi.Pointer<ffi.Void> _cookie;

  external ffi
      .Pointer<ffi.NativeFunction<ffi.Int Function(ffi.Pointer<ffi.Void>)>>
      _close;

  external ffi.Pointer<
      ffi.NativeFunction<
          ffi.Int Function(
              ffi.Pointer<ffi.Void>, ffi.Pointer<ffi.Char>, ffi.Int)>> _read;

  external ffi.Pointer<
      ffi.NativeFunction<
          fpos_t Function(ffi.Pointer<ffi.Void>, fpos_t, ffi.Int)>> _seek;

  external ffi.Pointer<
      ffi.NativeFunction<
          ffi.Int Function(
              ffi.Pointer<ffi.Void>, ffi.Pointer<ffi.Char>, ffi.Int)>> _write;

  external __sbuf _ub;

  external ffi.Pointer<__sFILEX> _extra;

  @ffi.Int()
  external int _ur;

  @ffi.Array.multi([3])
  external ffi.Array<ffi.UnsignedChar> _ubuf;

  @ffi.Array.multi([1])
  external ffi.Array<ffi.UnsignedChar> _nbuf;

  external __sbuf _lb;

  @ffi.Int()
  external int _blksize;

  @fpos_t()
  external int _offset;
}

typedef FILE = __sFILE;

sealed class ncintype_e {
  static const NCTYPE_UNKNOWN = 0;
  static const NCTYPE_PRESS = 1;
  static const NCTYPE_REPEAT = 2;
  static const NCTYPE_RELEASE = 3;
}

final class ncinput extends ffi.Struct {
  @ffi.Uint32()
  external int id;

  @ffi.Int()
  external int y;

  @ffi.Int()
  external int x;

  @ffi.Array.multi([5])
  external ffi.Array<ffi.Char> utf8;

  @ffi.Bool()
  external bool alt;

  @ffi.Bool()
  external bool shift;

  @ffi.Bool()
  external bool ctrl;

  @ffi.UnsignedInt()
  external int evtype;

  @ffi.UnsignedInt()
  external int modifiers;

  @ffi.Int()
  external int ypx;

  @ffi.Int()
  external int xpx;

  @ffi.Array.multi([4])
  external ffi.Array<ffi.Uint32> eff_text;
}

final class timespec extends ffi.Struct {
  @ffi.Long()
  external int tv_sec;

  @ffi.Long()
  external int tv_nsec;
}

final class ncplane_options extends ffi.Struct {
  @ffi.Int()
  external int y;

  @ffi.Int()
  external int x;

  @ffi.UnsignedInt()
  external int rows;

  @ffi.UnsignedInt()
  external int cols;

  external ffi.Pointer<ffi.Void> userptr;

  external ffi.Pointer<ffi.Char> name;

  external ffi
      .Pointer<ffi.NativeFunction<ffi.Int Function(ffi.Pointer<ncplane>)>>
      resizecb;

  @ffi.Uint64()
  external int flags;

  @ffi.UnsignedInt()
  external int margin_b;

  @ffi.UnsignedInt()
  external int margin_r;
}

final class ncpalette extends ffi.Struct {
  @ffi.Array.multi([256])
  external ffi.Array<ffi.Uint32> chans;
}

final class nccapabilities extends ffi.Struct {
  @ffi.UnsignedInt()
  external int colors;

  @ffi.Bool()
  external bool utf8;

  @ffi.Bool()
  external bool rgb;

  @ffi.Bool()
  external bool can_change_colors;

  @ffi.Bool()
  external bool halfblocks;

  @ffi.Bool()
  external bool quadrants;

  @ffi.Bool()
  external bool sextants;

  @ffi.Bool()
  external bool octants;

  @ffi.Bool()
  external bool braille;
}

sealed class ncpixelimpl_e {
  static const NCPIXEL_NONE = 0;
  static const NCPIXEL_SIXEL = 1;
  static const NCPIXEL_LINUXFB = 2;
  static const NCPIXEL_ITERM2 = 3;
  static const NCPIXEL_KITTY_STATIC = 4;
  static const NCPIXEL_KITTY_ANIMATED = 5;
  static const NCPIXEL_KITTY_SELFREF = 6;
}

final class ncstats extends ffi.Struct {
  @ffi.Uint64()
  external int renders;

  @ffi.Uint64()
  external int writeouts;

  @ffi.Uint64()
  external int failed_renders;

  @ffi.Uint64()
  external int failed_writeouts;

  @ffi.Uint64()
  external int raster_bytes;

  @ffi.Int64()
  external int raster_max_bytes;

  @ffi.Int64()
  external int raster_min_bytes;

  @ffi.Uint64()
  external int render_ns;

  @ffi.Int64()
  external int render_max_ns;

  @ffi.Int64()
  external int render_min_ns;

  @ffi.Uint64()
  external int raster_ns;

  @ffi.Int64()
  external int raster_max_ns;

  @ffi.Int64()
  external int raster_min_ns;

  @ffi.Uint64()
  external int writeout_ns;

  @ffi.Int64()
  external int writeout_max_ns;

  @ffi.Int64()
  external int writeout_min_ns;

  @ffi.Uint64()
  external int cellelisions;

  @ffi.Uint64()
  external int cellemissions;

  @ffi.Uint64()
  external int fgelisions;

  @ffi.Uint64()
  external int fgemissions;

  @ffi.Uint64()
  external int bgelisions;

  @ffi.Uint64()
  external int bgemissions;

  @ffi.Uint64()
  external int defaultelisions;

  @ffi.Uint64()
  external int defaultemissions;

  @ffi.Uint64()
  external int refreshes;

  @ffi.Uint64()
  external int sprixelemissions;

  @ffi.Uint64()
  external int sprixelelisions;

  @ffi.Uint64()
  external int sprixelbytes;

  @ffi.Uint64()
  external int appsync_updates;

  @ffi.Uint64()
  external int input_errors;

  @ffi.Uint64()
  external int input_events;

  @ffi.Uint64()
  external int hpa_gratuitous;

  @ffi.Uint64()
  external int cell_geo_changes;

  @ffi.Uint64()
  external int pixel_geo_changes;

  @ffi.Uint64()
  external int fbbytes;

  @ffi.UnsignedInt()
  external int planes;
}

typedef fadecbFunction = ffi.Int Function(ffi.Pointer<notcurses>,
    ffi.Pointer<ncplane>, ffi.Pointer<timespec>, ffi.Pointer<ffi.Void>);
typedef DartfadecbFunction = int Function(ffi.Pointer<notcurses>,
    ffi.Pointer<ncplane>, ffi.Pointer<timespec>, ffi.Pointer<ffi.Void>);
typedef fadecb = ffi.Pointer<ffi.NativeFunction<fadecbFunction>>;

final class ncvisual_options extends ffi.Struct {
  external ffi.Pointer<ncplane> n;

  @ffi.UnsignedInt()
  external int scaling;

  @ffi.Int()
  external int y;

  @ffi.Int()
  external int x;

  @ffi.UnsignedInt()
  external int begy;

  @ffi.UnsignedInt()
  external int begx;

  @ffi.UnsignedInt()
  external int leny;

  @ffi.UnsignedInt()
  external int lenx;

  @ffi.UnsignedInt()
  external int blitter;

  @ffi.Uint64()
  external int flags;

  @ffi.Uint32()
  external int transcolor;

  @ffi.UnsignedInt()
  external int pxoffy;

  @ffi.UnsignedInt()
  external int pxoffx;
}

final class ncvgeom extends ffi.Struct {
  @ffi.UnsignedInt()
  external int pixy;

  @ffi.UnsignedInt()
  external int pixx;

  @ffi.UnsignedInt()
  external int cdimy;

  @ffi.UnsignedInt()
  external int cdimx;

  @ffi.UnsignedInt()
  external int rpixy;

  @ffi.UnsignedInt()
  external int rpixx;

  @ffi.UnsignedInt()
  external int rcelly;

  @ffi.UnsignedInt()
  external int rcellx;

  @ffi.UnsignedInt()
  external int scaley;

  @ffi.UnsignedInt()
  external int scalex;

  @ffi.UnsignedInt()
  external int begy;

  @ffi.UnsignedInt()
  external int begx;

  @ffi.UnsignedInt()
  external int leny;

  @ffi.UnsignedInt()
  external int lenx;

  @ffi.UnsignedInt()
  external int maxpixely;

  @ffi.UnsignedInt()
  external int maxpixelx;

  @ffi.UnsignedInt()
  external int blitter;
}

typedef ncstreamcbFunction = ffi.Int Function(
    ffi.Pointer<ncvisual>,
    ffi.Pointer<ncvisual_options>,
    ffi.Pointer<timespec>,
    ffi.Pointer<ffi.Void>);
typedef DartncstreamcbFunction = int Function(
    ffi.Pointer<ncvisual>,
    ffi.Pointer<ncvisual_options>,
    ffi.Pointer<timespec>,
    ffi.Pointer<ffi.Void>);
typedef ncstreamcb = ffi.Pointer<ffi.NativeFunction<ncstreamcbFunction>>;

final class ncreel_options extends ffi.Struct {
  @ffi.UnsignedInt()
  external int bordermask;

  @ffi.Uint64()
  external int borderchan;

  @ffi.UnsignedInt()
  external int tabletmask;

  @ffi.Uint64()
  external int tabletchan;

  @ffi.Uint64()
  external int focusedchan;

  @ffi.Uint64()
  external int flags;
}

typedef tabletcbFunction = ffi.Int Function(
    ffi.Pointer<nctablet> t, ffi.Bool drawfromtop);
typedef DarttabletcbFunction = int Function(
    ffi.Pointer<nctablet> t, bool drawfromtop);
typedef tabletcb = ffi.Pointer<ffi.NativeFunction<tabletcbFunction>>;

final class ncselector_item extends ffi.Struct {
  external ffi.Pointer<ffi.Char> option;

  external ffi.Pointer<ffi.Char> desc;
}

final class ncselector_options extends ffi.Struct {
  external ffi.Pointer<ffi.Char> title;

  external ffi.Pointer<ffi.Char> secondary;

  external ffi.Pointer<ffi.Char> footer;

  external ffi.Pointer<ncselector_item> items;

  @ffi.UnsignedInt()
  external int defidx;

  @ffi.UnsignedInt()
  external int maxdisplay;

  @ffi.Uint64()
  external int opchannels;

  @ffi.Uint64()
  external int descchannels;

  @ffi.Uint64()
  external int titlechannels;

  @ffi.Uint64()
  external int footchannels;

  @ffi.Uint64()
  external int boxchannels;

  @ffi.Uint64()
  external int flags;
}

final class ncmselector_item extends ffi.Struct {
  external ffi.Pointer<ffi.Char> option;

  external ffi.Pointer<ffi.Char> desc;

  @ffi.Bool()
  external bool selected;
}

final class ncmultiselector_options extends ffi.Struct {
  external ffi.Pointer<ffi.Char> title;

  external ffi.Pointer<ffi.Char> secondary;

  external ffi.Pointer<ffi.Char> footer;

  external ffi.Pointer<ncmselector_item> items;

  @ffi.UnsignedInt()
  external int maxdisplay;

  @ffi.Uint64()
  external int opchannels;

  @ffi.Uint64()
  external int descchannels;

  @ffi.Uint64()
  external int titlechannels;

  @ffi.Uint64()
  external int footchannels;

  @ffi.Uint64()
  external int boxchannels;

  @ffi.Uint64()
  external int flags;
}

final class nctree_item extends ffi.Struct {
  external ffi.Pointer<ffi.Void> curry;

  external ffi.Pointer<nctree_item> subs;

  @ffi.UnsignedInt()
  external int subcount;
}

final class nctree_options extends ffi.Struct {
  external ffi.Pointer<nctree_item> items;

  @ffi.UnsignedInt()
  external int count;

  external ffi.Pointer<
      ffi.NativeFunction<
          ffi.Int Function(
              ffi.Pointer<ncplane>, ffi.Pointer<ffi.Void>, ffi.Int)>> nctreecb;

  @ffi.Int()
  external int indentcols;

  @ffi.Uint64()
  external int flags;
}

final class nctree extends ffi.Opaque {}

final class ncmenu_item extends ffi.Struct {
  external ffi.Pointer<ffi.Char> desc;

  external ncinput shortcut;
}

final class ncmenu_section extends ffi.Struct {
  external ffi.Pointer<ffi.Char> name;

  @ffi.Int()
  external int itemcount;

  external ffi.Pointer<ncmenu_item> items;

  external ncinput shortcut;
}

final class ncmenu_options extends ffi.Struct {
  external ffi.Pointer<ncmenu_section> sections;

  @ffi.Int()
  external int sectioncount;

  @ffi.Uint64()
  external int headerchannels;

  @ffi.Uint64()
  external int sectionchannels;

  @ffi.Uint64()
  external int flags;
}

final class ncmenu extends ffi.Opaque {}

final class ncprogbar_options extends ffi.Struct {
  @ffi.Uint32()
  external int ulchannel;

  @ffi.Uint32()
  external int urchannel;

  @ffi.Uint32()
  external int blchannel;

  @ffi.Uint32()
  external int brchannel;

  @ffi.Uint64()
  external int flags;
}

final class nctabbed_options extends ffi.Struct {
  @ffi.Uint64()
  external int selchan;

  @ffi.Uint64()
  external int hdrchan;

  @ffi.Uint64()
  external int sepchan;

  external ffi.Pointer<ffi.Char> separator;

  @ffi.Uint64()
  external int flags;
}

typedef tabcbFunction = ffi.Void Function(ffi.Pointer<nctab> t,
    ffi.Pointer<ncplane> ncp, ffi.Pointer<ffi.Void> curry);
typedef DarttabcbFunction = void Function(ffi.Pointer<nctab> t,
    ffi.Pointer<ncplane> ncp, ffi.Pointer<ffi.Void> curry);
typedef tabcb = ffi.Pointer<ffi.NativeFunction<tabcbFunction>>;

final class ncplot_options extends ffi.Struct {
  @ffi.Uint64()
  external int maxchannels;

  @ffi.Uint64()
  external int minchannels;

  @ffi.Uint16()
  external int legendstyle;

  @ffi.UnsignedInt()
  external int gridtype;

  @ffi.Int()
  external int rangex;

  external ffi.Pointer<ffi.Char> title;

  @ffi.Uint64()
  external int flags;
}

typedef ncfdplane_callbackFunction = ffi.Int Function(ffi.Pointer<ncfdplane> n,
    ffi.Pointer<ffi.Void> buf, ffi.Size s, ffi.Pointer<ffi.Void> curry);
typedef Dartncfdplane_callbackFunction = int Function(ffi.Pointer<ncfdplane> n,
    ffi.Pointer<ffi.Void> buf, int s, ffi.Pointer<ffi.Void> curry);
typedef ncfdplane_callback
    = ffi.Pointer<ffi.NativeFunction<ncfdplane_callbackFunction>>;
typedef ncfdplane_done_cbFunction = ffi.Int Function(
    ffi.Pointer<ncfdplane> n, ffi.Int fderrno, ffi.Pointer<ffi.Void> curry);
typedef Dartncfdplane_done_cbFunction = int Function(
    ffi.Pointer<ncfdplane> n, int fderrno, ffi.Pointer<ffi.Void> curry);
typedef ncfdplane_done_cb
    = ffi.Pointer<ffi.NativeFunction<ncfdplane_done_cbFunction>>;

final class ncfdplane_options extends ffi.Struct {
  external ffi.Pointer<ffi.Void> curry;

  @ffi.Bool()
  external bool follow;

  @ffi.Uint64()
  external int flags;
}

final class ncsubproc_options extends ffi.Struct {
  external ffi.Pointer<ffi.Void> curry;

  @ffi.Uint64()
  external int restart_period;

  @ffi.Uint64()
  external int flags;
}

final class ncreader_options extends ffi.Struct {
  @ffi.Uint64()
  external int tchannels;

  @ffi.Uint32()
  external int tattrword;

  @ffi.Uint64()
  external int flags;
}

typedef ncdirectv = ncplane;
typedef ncdirectf = ncvisual;

const int NCALIGN_TOP = 1;

const int NCALIGN_BOTTOM = 3;

const int NCALPHA_HIGHCONTRAST = 805306368;

const int NCALPHA_TRANSPARENT = 536870912;

const int NCALPHA_BLEND = 268435456;

const int NCALPHA_OPAQUE = 0;

const int NCPALETTESIZE = 256;

const int NC_NOBACKGROUND_MASK = -8718968878589280256;

const int NC_BGDEFAULT_MASK = 1073741824;

const int NC_BG_RGB_MASK = 16777215;

const int NC_BG_PALETTE = 134217728;

const int NC_BG_ALPHA_MASK = 805306368;

const int WCHAR_MAX_UTF8BYTES = 4;

const int NCSTYLE_MASK = 65535;

const int NCSTYLE_ITALIC = 16;

const int NCSTYLE_UNDERLINE = 8;

const int NCSTYLE_UNDERCURL = 4;

const int NCSTYLE_BOLD = 2;

const int NCSTYLE_STRUCK = 1;

const int NCSTYLE_NONE = 0;

const int NCOPTION_INHIBIT_SETLOCALE = 1;

const int NCOPTION_NO_CLEAR_BITMAPS = 2;

const int NCOPTION_NO_WINCH_SIGHANDLER = 4;

const int NCOPTION_NO_QUIT_SIGHANDLERS = 8;

const int NCOPTION_PRESERVE_CURSOR = 16;

const int NCOPTION_SUPPRESS_BANNERS = 32;

const int NCOPTION_NO_ALTERNATE_SCREEN = 64;

const int NCOPTION_NO_FONT_CHANGES = 128;

const int NCOPTION_DRAIN_INPUT = 256;

const int NCOPTION_SCROLLING = 512;

const int NCOPTION_CLI_MODE = 594;

const int NCINPUT_MAX_EFF_TEXT_CODEPOINTS = 4;

const int NCMICE_NO_EVENTS = 0;

const int NCMICE_MOVE_EVENT = 1;

const int NCMICE_BUTTON_EVENT = 2;

const int NCMICE_DRAG_EVENT = 4;

const int NCMICE_ALL_EVENTS = 7;

const int NCPLANE_OPTION_HORALIGNED = 1;

const int NCPLANE_OPTION_VERALIGNED = 2;

const int NCPLANE_OPTION_MARGINALIZED = 4;

const int NCPLANE_OPTION_FIXED = 8;

const int NCPLANE_OPTION_AUTOGROW = 16;

const int NCPLANE_OPTION_VSCROLL = 32;

const int NCBOXMASK_TOP = 1;

const int NCBOXMASK_RIGHT = 2;

const int NCBOXMASK_BOTTOM = 4;

const int NCBOXMASK_LEFT = 8;

const int NCBOXGRAD_TOP = 16;

const int NCBOXGRAD_RIGHT = 32;

const int NCBOXGRAD_BOTTOM = 64;

const int NCBOXGRAD_LEFT = 128;

const int NCBOXCORNER_MASK = 768;

const int NCBOXCORNER_SHIFT = 8;

const int NCVISUAL_OPTION_NODEGRADE = 1;

const int NCVISUAL_OPTION_BLEND = 2;

const int NCVISUAL_OPTION_HORALIGNED = 4;

const int NCVISUAL_OPTION_VERALIGNED = 8;

const int NCVISUAL_OPTION_ADDALPHA = 16;

const int NCVISUAL_OPTION_CHILDPLANE = 32;

const int NCVISUAL_OPTION_NOINTERPOLATE = 64;

const int NCREEL_OPTION_INFINITESCROLL = 1;

const int NCREEL_OPTION_CIRCULAR = 2;

const int NCPREFIXCOLUMNS = 7;

const int NCIPREFIXCOLUMNS = 8;

const int NCBPREFIXCOLUMNS = 9;

const int NCPREFIXSTRLEN = 8;

const int NCIPREFIXSTRLEN = 9;

const int NCBPREFIXSTRLEN = 10;

const int NCMENU_OPTION_BOTTOM = 1;

const int NCMENU_OPTION_HIDING = 2;

const int NCPROGBAR_OPTION_RETROGRADE = 1;

const int NCTABBED_OPTION_BOTTOM = 1;

const int NCPLOT_OPTION_LABELTICKSD = 1;

const int NCPLOT_OPTION_EXPONENTIALD = 2;

const int NCPLOT_OPTION_VERTICALI = 4;

const int NCPLOT_OPTION_NODEGRADE = 8;

const int NCPLOT_OPTION_DETECTMAXONLY = 16;

const int NCPLOT_OPTION_PRINTSAMPLE = 32;

const int NCREADER_OPTION_HORSCROLL = 1;

const int NCREADER_OPTION_VERSCROLL = 2;

const int NCREADER_OPTION_NOCMDKEYS = 4;

const int NCREADER_OPTION_CURSOR = 8;

const int NCDIRECT_OPTION_INHIBIT_SETLOCALE = 1;

const int NCDIRECT_OPTION_INHIBIT_CBREAK = 2;

const int NCDIRECT_OPTION_DRAIN_INPUT = 4;

const int NCDIRECT_OPTION_NO_QUIT_SIGHANDLERS = 8;

const int NCDIRECT_OPTION_VERBOSE = 16;

const int NCDIRECT_OPTION_VERY_VERBOSE = 32;
