// ignore_for_file: camel_case_types
// ignore_for_file: non_constant_identifier_names
// ignore_for_file: unused_element
// ignore_for_file: unused_field
// ignore_for_file: constant_identifier_names
// ignore_for_file: directives_ordering

// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint, unused_import
@ffi.DefaultAsset('package:dart_notcurses/dart_notcurses.dart')
library;

import 'dart:ffi' as ffi;
import './notcurses_g.dart' as main;

@ffi.Native<ffi.Bool Function(ffi.Pointer<nccapabilities>)>()
external bool nccapability_canchangecolor(
  ffi.Pointer<nccapabilities> caps,
);

@ffi.Native<ffi.Bool Function(ffi.Pointer<nccell>)>()
external bool nccell_bg_default_p(
  ffi.Pointer<nccell> cl,
);

@ffi.Native<ffi.Bool Function(ffi.Pointer<nccell>)>()
external bool nccell_bg_palindex_p(
  ffi.Pointer<nccell> cl,
);

@ffi.Native<ffi.Bool Function(ffi.Pointer<nccell>)>()
external bool nccell_double_wide_p(
  ffi.Pointer<nccell> c,
);

@ffi.Native<ffi.Bool Function(ffi.Pointer<nccell>)>()
external bool nccell_fg_default_p(
  ffi.Pointer<nccell> cl,
);

@ffi.Native<ffi.Bool Function(ffi.Pointer<nccell>)>()
external bool nccell_fg_palindex_p(
  ffi.Pointer<nccell> cl,
);

@ffi.Native<ffi.Bool Function(ffi.Pointer<nccell>)>()
external bool nccell_wide_left_p(
  ffi.Pointer<nccell> c,
);

@ffi.Native<ffi.Bool Function(ffi.Pointer<nccell>)>()
external bool nccell_wide_right_p(
  ffi.Pointer<nccell> c,
);

@ffi.Native<
    ffi.Bool Function(ffi.Pointer<main.ncplane>, ffi.Pointer<nccell>,
        ffi.Pointer<main.ncplane>, ffi.Pointer<nccell>)>()
external bool nccellcmp(
  ffi.Pointer<main.ncplane> n1,
  ffi.Pointer<nccell> c1,
  ffi.Pointer<main.ncplane> n2,
  ffi.Pointer<nccell> c2,
);

@ffi.Native<ffi.Bool Function(ffi.Uint32)>()
external bool ncchannel_default_p(
  int channel,
);

@ffi.Native<ffi.Bool Function(ffi.Uint32)>()
external bool ncchannel_palindex_p(
  int channel,
);

@ffi.Native<ffi.Bool Function(ffi.Uint32)>()
external bool ncchannel_rgb_p(
  int channel,
);

@ffi.Native<ffi.Bool Function(ffi.Uint64)>()
external bool ncchannels_bg_default_p(
  int channels,
);

@ffi.Native<ffi.Bool Function(ffi.Uint64)>()
external bool ncchannels_bg_palindex_p(
  int channels,
);

@ffi.Native<ffi.Bool Function(ffi.Uint64)>()
external bool ncchannels_bg_rgb_p(
  int channels,
);

@ffi.Native<ffi.Bool Function(ffi.Uint64)>()
external bool ncchannels_fg_default_p(
  int channels,
);

@ffi.Native<ffi.Bool Function(ffi.Uint64)>()
external bool ncchannels_fg_palindex_p(
  int channels,
);

@ffi.Native<ffi.Bool Function(ffi.Uint64)>()
external bool ncchannels_fg_rgb_p(
  int channels,
);

@ffi.Native<ffi.Bool Function(ffi.Pointer<main.ncdirect>)>()
external bool ncdirect_canbraille(
  ffi.Pointer<main.ncdirect> nc,
);

@ffi.Native<ffi.Bool Function(ffi.Pointer<main.ncdirect>)>()
external bool ncdirect_canchangecolor(
  ffi.Pointer<main.ncdirect> n,
);

@ffi.Native<ffi.Bool Function(ffi.Pointer<main.ncdirect>)>()
external bool ncdirect_canfade(
  ffi.Pointer<main.ncdirect> n,
);

@ffi.Native<ffi.Bool Function(ffi.Pointer<main.ncdirect>)>()
external bool ncdirect_canhalfblock(
  ffi.Pointer<main.ncdirect> nc,
);

@ffi.Native<ffi.Bool Function(ffi.Pointer<main.ncdirect>)>()
external bool ncdirect_canoctant(
  ffi.Pointer<main.ncdirect> nc,
);

@ffi.Native<ffi.Bool Function(ffi.Pointer<main.ncdirect>)>()
external bool ncdirect_canopen_images(
  ffi.Pointer<main.ncdirect> n,
);

@ffi.Native<ffi.Bool Function(ffi.Pointer<main.ncdirect>)>()
external bool ncdirect_canopen_videos(
  ffi.Pointer<main.ncdirect> n,
);

@ffi.Native<ffi.Bool Function(ffi.Pointer<main.ncdirect>)>()
external bool ncdirect_canquadrant(
  ffi.Pointer<main.ncdirect> nc,
);

@ffi.Native<ffi.Bool Function(ffi.Pointer<main.ncdirect>)>()
external bool ncdirect_cansextant(
  ffi.Pointer<main.ncdirect> nc,
);

@ffi.Native<ffi.Bool Function(ffi.Pointer<main.ncdirect>)>()
external bool ncdirect_cantruecolor(
  ffi.Pointer<main.ncdirect> n,
);

@ffi.Native<ffi.Bool Function(ffi.Pointer<ncinput>)>()
external bool ncinput_alt_p(
  ffi.Pointer<ncinput> n,
);

@ffi.Native<ffi.Bool Function(ffi.Pointer<ncinput>)>()
external bool ncinput_capslock_p(
  ffi.Pointer<ncinput> n,
);

@ffi.Native<ffi.Bool Function(ffi.Pointer<ncinput>)>()
external bool ncinput_ctrl_p(
  ffi.Pointer<ncinput> n,
);

@ffi.Native<ffi.Bool Function(ffi.Pointer<ncinput>, ffi.Pointer<ncinput>)>()
external bool ncinput_equal_p(
  ffi.Pointer<ncinput> n1,
  ffi.Pointer<ncinput> n2,
);

@ffi.Native<ffi.Bool Function(ffi.Pointer<ncinput>)>()
external bool ncinput_hyper_p(
  ffi.Pointer<ncinput> n,
);

@ffi.Native<ffi.Bool Function(ffi.Pointer<ncinput>)>()
external bool ncinput_meta_p(
  ffi.Pointer<ncinput> n,
);

@ffi.Native<ffi.Bool Function(ffi.Pointer<ncinput>)>()
external bool ncinput_nomod_p(
  ffi.Pointer<ncinput> ni,
);

@ffi.Native<ffi.Bool Function(ffi.Pointer<ncinput>)>()
external bool ncinput_numlock_p(
  ffi.Pointer<ncinput> n,
);

@ffi.Native<ffi.Bool Function(ffi.Pointer<ncinput>)>()
external bool ncinput_shift_p(
  ffi.Pointer<ncinput> n,
);

@ffi.Native<ffi.Bool Function(ffi.Pointer<ncinput>)>()
external bool ncinput_super_p(
  ffi.Pointer<ncinput> n,
);

@ffi.Native<ffi.Bool Function(ffi.Uint32)>()
external bool nckey_mouse_p(
  int r,
);

@ffi.Native<ffi.Bool Function(ffi.Uint32)>()
external bool nckey_pua_p(
  int w,
);

@ffi.Native<ffi.Bool Function(ffi.Uint32)>()
external bool nckey_supppuaa_p(
  int w,
);

@ffi.Native<ffi.Bool Function(ffi.Uint32)>()
external bool nckey_supppuab_p(
  int w,
);

@ffi.Native<ffi.Bool Function(ffi.Uint32)>()
external bool nckey_synthesized_p(
  int w,
);

@ffi.Native<ffi.Bool Function(ffi.Pointer<main.ncplane>)>()
external bool ncplane_bg_default_p(
  ffi.Pointer<main.ncplane> n,
);

@ffi.Native<ffi.Bool Function(ffi.Pointer<main.ncplane>)>()
external bool ncplane_fg_default_p(
  ffi.Pointer<main.ncplane> n,
);

@ffi.Native<ffi.Bool Function(ffi.Pointer<main.notcurses>)>()
external bool notcurses_canbraille(
  ffi.Pointer<main.notcurses> nc,
);

@ffi.Native<ffi.Bool Function(ffi.Pointer<main.notcurses>)>()
external bool notcurses_canchangecolor(
  ffi.Pointer<main.notcurses> nc,
);

@ffi.Native<ffi.Bool Function(ffi.Pointer<main.notcurses>)>()
external bool notcurses_canfade(
  ffi.Pointer<main.notcurses> n,
);

@ffi.Native<ffi.Bool Function(ffi.Pointer<main.notcurses>)>()
external bool notcurses_canhalfblock(
  ffi.Pointer<main.notcurses> nc,
);

@ffi.Native<ffi.Bool Function(ffi.Pointer<main.notcurses>)>()
external bool notcurses_canoctant(
  ffi.Pointer<main.notcurses> nc,
);

@ffi.Native<ffi.Bool Function(ffi.Pointer<main.notcurses>)>()
external bool notcurses_canpixel(
  ffi.Pointer<main.notcurses> nc,
);

@ffi.Native<ffi.Bool Function(ffi.Pointer<main.notcurses>)>()
external bool notcurses_canquadrant(
  ffi.Pointer<main.notcurses> nc,
);

@ffi.Native<ffi.Bool Function(ffi.Pointer<main.notcurses>)>()
external bool notcurses_cansextant(
  ffi.Pointer<main.notcurses> nc,
);

@ffi.Native<ffi.Bool Function(ffi.Pointer<main.notcurses>)>()
external bool notcurses_cantruecolor(
  ffi.Pointer<main.notcurses> nc,
);

@ffi.Native<ffi.Bool Function(ffi.Pointer<main.notcurses>)>()
external bool notcurses_canutf8(
  ffi.Pointer<main.notcurses> nc,
);

@ffi.Native<
    ffi.Pointer<ffi.Char> Function(
        ffi.Pointer<main.ncplane>,
        ffi.Pointer<nccell>,
        ffi.Pointer<ffi.Uint16>,
        ffi.Pointer<ffi.Uint64>)>()
external ffi.Pointer<ffi.Char> nccell_extract(
  ffi.Pointer<main.ncplane> n,
  ffi.Pointer<nccell> c,
  ffi.Pointer<ffi.Uint16> stylemask,
  ffi.Pointer<ffi.Uint64> channels,
);

@ffi.Native<
    ffi.Pointer<ffi.Char> Function(
        ffi.Pointer<main.ncplane>, ffi.Pointer<nccell>)>()
external ffi.Pointer<ffi.Char> nccell_strdup(
  ffi.Pointer<main.ncplane> n,
  ffi.Pointer<nccell> c,
);

@ffi.Native<ffi.Pointer<ffi.Char> Function(ffi.Pointer<ffi.WChar>)>()
external ffi.Pointer<ffi.Char> ncwcsrtombs(
  ffi.Pointer<ffi.WChar> src,
);

@ffi.Native<
    ffi.Pointer<ffi.Char> Function(
        uintmax_t, uintmax_t, ffi.Pointer<ffi.Char>, ffi.Int)>()
external ffi.Pointer<ffi.Char> ncbprefix(
  int val,
  int decimal,
  ffi.Pointer<ffi.Char> buf,
  int omitdec,
);

@ffi.Native<
    ffi.Pointer<ffi.Char> Function(
        uintmax_t, uintmax_t, ffi.Pointer<ffi.Char>, ffi.Int)>()
external ffi.Pointer<ffi.Char> nciprefix(
  int val,
  int decimal,
  ffi.Pointer<ffi.Char> buf,
  int omitdec,
);

@ffi.Native<
    ffi.Pointer<ffi.Char> Function(
        uintmax_t, uintmax_t, ffi.Pointer<ffi.Char>, ffi.Int)>()
external ffi.Pointer<ffi.Char> ncqprefix(
  int val,
  int decimal,
  ffi.Pointer<ffi.Char> buf,
  int omitdec,
);

@ffi.Native<
    ffi.Pointer<main.ncplane> Function(ffi.Pointer<main.notcurses>,
        ffi.Pointer<ffi.UnsignedInt>, ffi.Pointer<ffi.UnsignedInt>)>()
external ffi.Pointer<main.ncplane> notcurses_stddim_yx_const(
  ffi.Pointer<main.notcurses> nc,
  ffi.Pointer<ffi.UnsignedInt> y,
  ffi.Pointer<ffi.UnsignedInt> x,
);

@ffi.Native<
    ffi.Int Function(
        ffi.Pointer<main.ncplane>, ffi.Pointer<nccell>, ffi.Char)>()
external int nccell_load_char(
  ffi.Pointer<main.ncplane> n,
  ffi.Pointer<nccell> c,
  int ch,
);

@ffi.Native<
    ffi.Int Function(
        ffi.Pointer<main.ncplane>, ffi.Pointer<nccell>, ffi.Uint32)>()
external int nccell_load_egc32(
  ffi.Pointer<main.ncplane> n,
  ffi.Pointer<nccell> c,
  int egc,
);

@ffi.Native<
    ffi.Int Function(
        ffi.Pointer<main.ncplane>, ffi.Pointer<nccell>, ffi.Uint32)>()
external int nccell_load_ucs32(
  ffi.Pointer<main.ncplane> n,
  ffi.Pointer<nccell> c,
  int u,
);

@ffi.Native<
    ffi.Int Function(ffi.Pointer<main.ncplane>, ffi.Pointer<nccell>,
        ffi.Pointer<ffi.Char>, ffi.Uint16, ffi.Uint64)>()
external int nccell_prime(
  ffi.Pointer<main.ncplane> n,
  ffi.Pointer<nccell> c,
  ffi.Pointer<ffi.Char> gcluster,
  int stylemask,
  int channels,
);

@ffi.Native<ffi.Int Function(ffi.Pointer<nccell>, ffi.UnsignedInt)>()
external int nccell_set_bg_alpha(
  ffi.Pointer<nccell> c,
  int alpha,
);

@ffi.Native<ffi.Int Function(ffi.Pointer<nccell>, ffi.UnsignedInt)>()
external int nccell_set_bg_palindex(
  ffi.Pointer<nccell> cl,
  int idx,
);

@ffi.Native<ffi.Int Function(ffi.Pointer<nccell>, ffi.Uint32)>()
external int nccell_set_bg_rgb(
  ffi.Pointer<nccell> c,
  int channel,
);

@ffi.Native<
    ffi.Int Function(ffi.Pointer<nccell>, ffi.UnsignedInt, ffi.UnsignedInt,
        ffi.UnsignedInt)>()
external int nccell_set_bg_rgb8(
  ffi.Pointer<nccell> cl,
  int r,
  int g,
  int b,
);

@ffi.Native<ffi.Int Function(ffi.Pointer<nccell>, ffi.UnsignedInt)>()
external int nccell_set_fg_alpha(
  ffi.Pointer<nccell> c,
  int alpha,
);

@ffi.Native<ffi.Int Function(ffi.Pointer<nccell>, ffi.UnsignedInt)>()
external int nccell_set_fg_palindex(
  ffi.Pointer<nccell> cl,
  int idx,
);

@ffi.Native<ffi.Int Function(ffi.Pointer<nccell>, ffi.Uint32)>()
external int nccell_set_fg_rgb(
  ffi.Pointer<nccell> c,
  int channel,
);

@ffi.Native<
    ffi.Int Function(ffi.Pointer<nccell>, ffi.UnsignedInt, ffi.UnsignedInt,
        ffi.UnsignedInt)>()
external int nccell_set_fg_rgb8(
  ffi.Pointer<nccell> cl,
  int r,
  int g,
  int b,
);

@ffi.Native<
    ffi.Int Function(
        ffi.Pointer<main.ncplane>,
        ffi.Uint16,
        ffi.Uint64,
        ffi.Pointer<nccell>,
        ffi.Pointer<nccell>,
        ffi.Pointer<nccell>,
        ffi.Pointer<nccell>,
        ffi.Pointer<nccell>,
        ffi.Pointer<nccell>)>()
external int nccells_ascii_box(
  ffi.Pointer<main.ncplane> n,
  int attr,
  int channels,
  ffi.Pointer<nccell> ul,
  ffi.Pointer<nccell> ur,
  ffi.Pointer<nccell> ll,
  ffi.Pointer<nccell> lr,
  ffi.Pointer<nccell> hl,
  ffi.Pointer<nccell> vl,
);

@ffi.Native<
    ffi.Int Function(
        ffi.Pointer<main.ncplane>,
        ffi.Uint16,
        ffi.Uint64,
        ffi.Pointer<nccell>,
        ffi.Pointer<nccell>,
        ffi.Pointer<nccell>,
        ffi.Pointer<nccell>,
        ffi.Pointer<nccell>,
        ffi.Pointer<nccell>)>()
external int nccells_double_box(
  ffi.Pointer<main.ncplane> n,
  int attr,
  int channels,
  ffi.Pointer<nccell> ul,
  ffi.Pointer<nccell> ur,
  ffi.Pointer<nccell> ll,
  ffi.Pointer<nccell> lr,
  ffi.Pointer<nccell> hl,
  ffi.Pointer<nccell> vl,
);

@ffi.Native<
    ffi.Int Function(
        ffi.Pointer<main.ncplane>,
        ffi.Uint16,
        ffi.Uint64,
        ffi.Pointer<nccell>,
        ffi.Pointer<nccell>,
        ffi.Pointer<nccell>,
        ffi.Pointer<nccell>,
        ffi.Pointer<nccell>,
        ffi.Pointer<nccell>)>()
external int nccells_heavy_box(
  ffi.Pointer<main.ncplane> n,
  int attr,
  int channels,
  ffi.Pointer<nccell> ul,
  ffi.Pointer<nccell> ur,
  ffi.Pointer<nccell> ll,
  ffi.Pointer<nccell> lr,
  ffi.Pointer<nccell> hl,
  ffi.Pointer<nccell> vl,
);

@ffi.Native<
    ffi.Int Function(
        ffi.Pointer<main.ncplane>,
        ffi.Uint16,
        ffi.Uint64,
        ffi.Pointer<nccell>,
        ffi.Pointer<nccell>,
        ffi.Pointer<nccell>,
        ffi.Pointer<nccell>,
        ffi.Pointer<nccell>,
        ffi.Pointer<nccell>)>()
external int nccells_light_box(
  ffi.Pointer<main.ncplane> n,
  int attr,
  int channels,
  ffi.Pointer<nccell> ul,
  ffi.Pointer<nccell> ur,
  ffi.Pointer<nccell> ll,
  ffi.Pointer<nccell> lr,
  ffi.Pointer<nccell> hl,
  ffi.Pointer<nccell> vl,
);

@ffi.Native<
    ffi.Int Function(
        ffi.Pointer<main.ncplane>,
        ffi.Uint16,
        ffi.Uint64,
        ffi.Pointer<nccell>,
        ffi.Pointer<nccell>,
        ffi.Pointer<nccell>,
        ffi.Pointer<nccell>,
        ffi.Pointer<nccell>,
        ffi.Pointer<nccell>,
        ffi.Pointer<ffi.Char>)>()
external int nccells_load_box(
  ffi.Pointer<main.ncplane> n,
  int styles,
  int channels,
  ffi.Pointer<nccell> ul,
  ffi.Pointer<nccell> ur,
  ffi.Pointer<nccell> ll,
  ffi.Pointer<nccell> lr,
  ffi.Pointer<nccell> hl,
  ffi.Pointer<nccell> vl,
  ffi.Pointer<ffi.Char> gclusters,
);

@ffi.Native<
    ffi.Int Function(
        ffi.Pointer<main.ncplane>,
        ffi.Uint16,
        ffi.Uint64,
        ffi.Pointer<nccell>,
        ffi.Pointer<nccell>,
        ffi.Pointer<nccell>,
        ffi.Pointer<nccell>,
        ffi.Pointer<nccell>,
        ffi.Pointer<nccell>)>()
external int nccells_rounded_box(
  ffi.Pointer<main.ncplane> n,
  int attr,
  int channels,
  ffi.Pointer<nccell> ul,
  ffi.Pointer<nccell> ur,
  ffi.Pointer<nccell> ll,
  ffi.Pointer<nccell> lr,
  ffi.Pointer<nccell> hl,
  ffi.Pointer<nccell> vl,
);

@ffi.Native<ffi.Int Function(ffi.Pointer<ffi.Uint32>, ffi.Uint32)>()
external int ncchannel_set(
  ffi.Pointer<ffi.Uint32> channel,
  int rgb,
);

@ffi.Native<ffi.Int Function(ffi.Pointer<ffi.Uint32>, ffi.UnsignedInt)>()
external int ncchannel_set_alpha(
  ffi.Pointer<ffi.Uint32> channel,
  int alpha,
);

@ffi.Native<ffi.Int Function(ffi.Pointer<ffi.Uint32>, ffi.UnsignedInt)>()
external int ncchannel_set_palindex(
  ffi.Pointer<ffi.Uint32> channel,
  int idx,
);

@ffi.Native<
    ffi.Int Function(ffi.Pointer<ffi.Uint32>, ffi.UnsignedInt, ffi.UnsignedInt,
        ffi.UnsignedInt)>()
external int ncchannel_set_rgb8(
  ffi.Pointer<ffi.Uint32> channel,
  int r,
  int g,
  int b,
);

@ffi.Native<ffi.Int Function(ffi.Pointer<ffi.Uint64>, ffi.UnsignedInt)>()
external int ncchannels_set_bg_alpha(
  ffi.Pointer<ffi.Uint64> channels,
  int alpha,
);

@ffi.Native<ffi.Int Function(ffi.Pointer<ffi.Uint64>, ffi.UnsignedInt)>()
external int ncchannels_set_bg_palindex(
  ffi.Pointer<ffi.Uint64> channels,
  int idx,
);

@ffi.Native<ffi.Int Function(ffi.Pointer<ffi.Uint64>, ffi.UnsignedInt)>()
external int ncchannels_set_bg_rgb(
  ffi.Pointer<ffi.Uint64> channels,
  int rgb,
);

@ffi.Native<
    ffi.Int Function(ffi.Pointer<ffi.Uint64>, ffi.UnsignedInt, ffi.UnsignedInt,
        ffi.UnsignedInt)>()
external int ncchannels_set_bg_rgb8(
  ffi.Pointer<ffi.Uint64> channels,
  int r,
  int g,
  int b,
);

@ffi.Native<ffi.Int Function(ffi.Pointer<ffi.Uint64>, ffi.UnsignedInt)>()
external int ncchannels_set_fg_alpha(
  ffi.Pointer<ffi.Uint64> channels,
  int alpha,
);

@ffi.Native<ffi.Int Function(ffi.Pointer<ffi.Uint64>, ffi.UnsignedInt)>()
external int ncchannels_set_fg_palindex(
  ffi.Pointer<ffi.Uint64> channels,
  int idx,
);

@ffi.Native<ffi.Int Function(ffi.Pointer<ffi.Uint64>, ffi.UnsignedInt)>()
external int ncchannels_set_fg_rgb(
  ffi.Pointer<ffi.Uint64> channels,
  int rgb,
);

@ffi.Native<
    ffi.Int Function(ffi.Pointer<ffi.Uint64>, ffi.UnsignedInt, ffi.UnsignedInt,
        ffi.UnsignedInt)>()
external int ncchannels_set_fg_rgb8(
  ffi.Pointer<ffi.Uint64> channels,
  int r,
  int g,
  int b,
);

@ffi.Native<
    ffi.Int Function(
        ffi.Pointer<main.ncdirect>,
        ffi.Uint64,
        ffi.Uint64,
        ffi.Uint64,
        ffi.Uint64,
        ffi.UnsignedInt,
        ffi.UnsignedInt,
        ffi.UnsignedInt)>()
external int ncdirect_ascii_box(
  ffi.Pointer<main.ncdirect> n,
  int ul,
  int ur,
  int ll,
  int lr,
  int ylen,
  int xlen,
  int ctlword,
);

@ffi.Native<
    ffi.Int Function(
        ffi.Pointer<main.ncdirect>,
        ffi.Uint64,
        ffi.Uint64,
        ffi.Uint64,
        ffi.Uint64,
        ffi.UnsignedInt,
        ffi.UnsignedInt,
        ffi.UnsignedInt)>()
external int ncdirect_heavy_box(
  ffi.Pointer<main.ncdirect> n,
  int ul,
  int ur,
  int ll,
  int lr,
  int ylen,
  int xlen,
  int ctlword,
);

@ffi.Native<
    ffi.Int Function(
        ffi.Pointer<main.ncdirect>,
        ffi.Uint64,
        ffi.Uint64,
        ffi.Uint64,
        ffi.Uint64,
        ffi.UnsignedInt,
        ffi.UnsignedInt,
        ffi.UnsignedInt)>()
external int ncdirect_light_box(
  ffi.Pointer<main.ncdirect> n,
  int ul,
  int ur,
  int ll,
  int lr,
  int ylen,
  int xlen,
  int ctlword,
);

@ffi.Native<
    ffi.Int Function(ffi.Pointer<main.ncdirect>, ffi.UnsignedInt,
        ffi.UnsignedInt, ffi.UnsignedInt)>()
external int ncdirect_set_bg_rgb8(
  ffi.Pointer<main.ncdirect> nc,
  int r,
  int g,
  int b,
);

@ffi.Native<
    ffi.Int Function(ffi.Pointer<main.ncdirect>, ffi.UnsignedInt,
        ffi.UnsignedInt, ffi.UnsignedInt)>()
external int ncdirect_set_fg_rgb8(
  ffi.Pointer<main.ncdirect> nc,
  int r,
  int g,
  int b,
);

@ffi.Native<
    ffi.Int Function(
        ffi.Pointer<ncpalette>, ffi.Int, ffi.Pointer<ffi.Uint32>)>()
external int ncpalette_get(
  ffi.Pointer<ncpalette> p,
  int idx,
  ffi.Pointer<ffi.Uint32> palent,
);

@ffi.Native<
    ffi.Int Function(
        ffi.Pointer<ncpalette>,
        ffi.Int,
        ffi.Pointer<ffi.UnsignedInt>,
        ffi.Pointer<ffi.UnsignedInt>,
        ffi.Pointer<ffi.UnsignedInt>)>()
external int ncpalette_get_rgb8(
  ffi.Pointer<ncpalette> p,
  int idx,
  ffi.Pointer<ffi.UnsignedInt> r,
  ffi.Pointer<ffi.UnsignedInt> g,
  ffi.Pointer<ffi.UnsignedInt> b,
);

@ffi.Native<
    ffi.Int Function(ffi.Pointer<ncpalette>, ffi.Int, ffi.UnsignedInt)>()
external int ncpalette_set(
  ffi.Pointer<ncpalette> p,
  int idx,
  int rgb,
);

@ffi.Native<
    ffi.Int Function(ffi.Pointer<ncpalette>, ffi.Int, ffi.UnsignedInt,
        ffi.UnsignedInt, ffi.UnsignedInt)>()
external int ncpalette_set_rgb8(
  ffi.Pointer<ncpalette> p,
  int idx,
  int r,
  int g,
  int b,
);

@ffi.Native<ffi.Int Function(ffi.Pointer<ffi.Uint32>, ffi.UnsignedInt)>()
external int ncpixel_set_a(
  ffi.Pointer<ffi.Uint32> pixel,
  int a,
);

@ffi.Native<ffi.Int Function(ffi.Pointer<ffi.Uint32>, ffi.UnsignedInt)>()
external int ncpixel_set_b(
  ffi.Pointer<ffi.Uint32> pixel,
  int b,
);

@ffi.Native<ffi.Int Function(ffi.Pointer<ffi.Uint32>, ffi.UnsignedInt)>()
external int ncpixel_set_g(
  ffi.Pointer<ffi.Uint32> pixel,
  int g,
);

@ffi.Native<ffi.Int Function(ffi.Pointer<ffi.Uint32>, ffi.UnsignedInt)>()
external int ncpixel_set_r(
  ffi.Pointer<ffi.Uint32> pixel,
  int r,
);

@ffi.Native<
    ffi.Int Function(ffi.Pointer<ffi.Uint32>, ffi.UnsignedInt, ffi.UnsignedInt,
        ffi.UnsignedInt)>()
external int ncpixel_set_rgb8(
  ffi.Pointer<ffi.Uint32> pixel,
  int r,
  int g,
  int b,
);

@ffi.Native<
    ffi.Int Function(ffi.Pointer<main.ncplane>, ffi.Uint16, ffi.Uint64,
        ffi.UnsignedInt, ffi.UnsignedInt, ffi.UnsignedInt)>()
external int ncplane_ascii_box(
  ffi.Pointer<main.ncplane> n,
  int styles,
  int channels,
  int ylen,
  int xlen,
  int ctlword,
);

@ffi.Native<
    ffi.Int Function(
        ffi.Pointer<main.ncplane>,
        ffi.Pointer<nccell>,
        ffi.Pointer<nccell>,
        ffi.Pointer<nccell>,
        ffi.Pointer<nccell>,
        ffi.Pointer<nccell>,
        ffi.Pointer<nccell>,
        ffi.UnsignedInt,
        ffi.UnsignedInt,
        ffi.UnsignedInt)>()
external int ncplane_box_sized(
  ffi.Pointer<main.ncplane> n,
  ffi.Pointer<nccell> ul,
  ffi.Pointer<nccell> ur,
  ffi.Pointer<nccell> ll,
  ffi.Pointer<nccell> lr,
  ffi.Pointer<nccell> hline,
  ffi.Pointer<nccell> vline,
  int ystop,
  int xstop,
  int ctlword,
);

@ffi.Native<
    ffi.Int Function(ffi.Pointer<main.ncplane>, ffi.Pointer<main.ncplane>)>()
external int ncplane_descendant_p(
  ffi.Pointer<main.ncplane> n,
  ffi.Pointer<main.ncplane> ancestor,
);

@ffi.Native<
    ffi.Int Function(ffi.Pointer<main.ncplane>, ffi.Uint16, ffi.Uint64,
        ffi.UnsignedInt, ffi.UnsignedInt, ffi.UnsignedInt)>()
external int ncplane_double_box(
  ffi.Pointer<main.ncplane> n,
  int styles,
  int channels,
  int ylen,
  int xlen,
  int ctlword,
);

@ffi.Native<
    ffi.Int Function(ffi.Pointer<main.ncplane>, ffi.Uint16, ffi.Uint64,
        ffi.UnsignedInt, ffi.UnsignedInt, ffi.UnsignedInt)>()
external int ncplane_double_box_sized(
  ffi.Pointer<main.ncplane> n,
  int styles,
  int channels,
  int ylen,
  int xlen,
  int ctlword,
);

@ffi.Native<
    ffi.Int Function(ffi.Pointer<main.ncplane>, ffi.UnsignedInt, ffi.Int)>()
external int ncplane_halign(
  ffi.Pointer<main.ncplane> n,
  int align,
  int c,
);

@ffi.Native<
    ffi.Int Function(
        ffi.Pointer<main.ncplane>, ffi.Pointer<nccell>, ffi.UnsignedInt)>()
external int ncplane_hline(
  ffi.Pointer<main.ncplane> n,
  ffi.Pointer<nccell> c,
  int len,
);

@ffi.Native<ffi.Int Function(ffi.Pointer<main.ncplane>, ffi.Int, ffi.Int)>()
external int ncplane_move_rel(
  ffi.Pointer<main.ncplane> n,
  int y,
  int x,
);

@ffi.Native<
    ffi.Int Function(
        ffi.Pointer<main.ncplane>,
        ffi.Pointer<nccell>,
        ffi.Pointer<nccell>,
        ffi.Pointer<nccell>,
        ffi.Pointer<nccell>,
        ffi.Pointer<nccell>,
        ffi.Pointer<nccell>,
        ffi.UnsignedInt)>()
external int ncplane_perimeter(
  ffi.Pointer<main.ncplane> n,
  ffi.Pointer<nccell> ul,
  ffi.Pointer<nccell> ur,
  ffi.Pointer<nccell> ll,
  ffi.Pointer<nccell> lr,
  ffi.Pointer<nccell> hline,
  ffi.Pointer<nccell> vline,
  int ctlword,
);

@ffi.Native<
    ffi.Int Function(
        ffi.Pointer<main.ncplane>, ffi.Uint16, ffi.Uint64, ffi.UnsignedInt)>()
external int ncplane_perimeter_double(
  ffi.Pointer<main.ncplane> n,
  int stylemask,
  int channels,
  int ctlword,
);

@ffi.Native<
    ffi.Int Function(
        ffi.Pointer<main.ncplane>, ffi.Uint16, ffi.Uint64, ffi.UnsignedInt)>()
external int ncplane_perimeter_rounded(
  ffi.Pointer<main.ncplane> n,
  int stylemask,
  int channels,
  int ctlword,
);

@ffi.Native<
    ffi.Int Function(ffi.Pointer<main.ncplane>, ffi.Pointer<ffi.Char>)>()
external int ncplane_printf(
  ffi.Pointer<main.ncplane> n,
  ffi.Pointer<ffi.Char> format,
);

@ffi.Native<
    ffi.Int Function(ffi.Pointer<main.ncplane>, ffi.Int, ffi.UnsignedInt,
        ffi.Pointer<ffi.Char>)>()
external int ncplane_printf_aligned(
  ffi.Pointer<main.ncplane> n,
  int y,
  int align,
  ffi.Pointer<ffi.Char> format,
);

@ffi.Native<
    ffi.Int Function(ffi.Pointer<main.ncplane>, ffi.Pointer<ffi.Char>)>()
external int ncplane_printf_stained(
  ffi.Pointer<main.ncplane> n,
  ffi.Pointer<ffi.Char> format,
);

@ffi.Native<
    ffi.Int Function(
        ffi.Pointer<main.ncplane>, ffi.Int, ffi.Int, ffi.Pointer<ffi.Char>)>()
external int ncplane_printf_yx(
  ffi.Pointer<main.ncplane> n,
  int y,
  int x,
  ffi.Pointer<ffi.Char> format,
);

@ffi.Native<ffi.Int Function(ffi.Pointer<main.ncplane>, ffi.Pointer<nccell>)>()
external int ncplane_putc(
  ffi.Pointer<main.ncplane> n,
  ffi.Pointer<nccell> c,
);

@ffi.Native<ffi.Int Function(ffi.Pointer<main.ncplane>, ffi.Char)>()
external int ncplane_putchar(
  ffi.Pointer<main.ncplane> n,
  int c,
);

@ffi.Native<
    ffi.Int Function(ffi.Pointer<main.ncplane>, ffi.Int, ffi.Int, ffi.Char)>()
external int ncplane_putchar_yx(
  ffi.Pointer<main.ncplane> n,
  int y,
  int x,
  int c,
);

@ffi.Native<
    ffi.Int Function(ffi.Pointer<main.ncplane>, ffi.Pointer<ffi.Char>,
        ffi.Pointer<ffi.Size>)>()
external int ncplane_putegc(
  ffi.Pointer<main.ncplane> n,
  ffi.Pointer<ffi.Char> gclust,
  ffi.Pointer<ffi.Size> sbytes,
);

@ffi.Native<
    ffi.Int Function(
        ffi.Pointer<main.ncplane>, ffi.Size, ffi.Pointer<ffi.Char>)>()
external int ncplane_putnstr(
  ffi.Pointer<main.ncplane> n,
  int s,
  ffi.Pointer<ffi.Char> gclustarr,
);

@ffi.Native<
    ffi.Int Function(ffi.Pointer<main.ncplane>, ffi.Int, ffi.Int, ffi.Size,
        ffi.Pointer<ffi.Char>)>()
external int ncplane_putnstr_yx(
  ffi.Pointer<main.ncplane> n,
  int y,
  int x,
  int s,
  ffi.Pointer<ffi.Char> gclusters,
);

@ffi.Native<
    ffi.Int Function(ffi.Pointer<main.ncplane>, ffi.Pointer<ffi.Char>)>()
external int ncplane_putstr(
  ffi.Pointer<main.ncplane> n,
  ffi.Pointer<ffi.Char> gclustarr,
);

@ffi.Native<
    ffi.Int Function(ffi.Pointer<main.ncplane>, ffi.Int, ffi.UnsignedInt,
        ffi.Pointer<ffi.Char>)>()
external int ncplane_putstr_aligned(
  ffi.Pointer<main.ncplane> n,
  int y,
  int align,
  ffi.Pointer<ffi.Char> s,
);

@ffi.Native<
    ffi.Int Function(ffi.Pointer<main.ncplane>, ffi.Pointer<ffi.Char>)>()
external int ncplane_putstr_stained(
  ffi.Pointer<main.ncplane> n,
  ffi.Pointer<ffi.Char> gclusters,
);

@ffi.Native<
    ffi.Int Function(
        ffi.Pointer<main.ncplane>, ffi.Int, ffi.Int, ffi.Pointer<ffi.Char>)>()
external int ncplane_putstr_yx(
  ffi.Pointer<main.ncplane> n,
  int y,
  int x,
  ffi.Pointer<ffi.Char> gclusters,
);

@ffi.Native<
    ffi.Int Function(ffi.Pointer<main.ncplane>, ffi.Int, ffi.Int, ffi.Uint32)>()
external int ncplane_pututf32_yx(
  ffi.Pointer<main.ncplane> n,
  int y,
  int x,
  int u,
);

@ffi.Native<ffi.Int Function(ffi.Pointer<main.ncplane>, ffi.WChar)>()
external int ncplane_putwc(
  ffi.Pointer<main.ncplane> n,
  int w,
);

@ffi.Native<ffi.Int Function(ffi.Pointer<main.ncplane>, ffi.WChar)>()
external int ncplane_putwc_stained(
  ffi.Pointer<main.ncplane> n,
  int w,
);

@ffi.Native<
    ffi.Int Function(ffi.Pointer<main.ncplane>, ffi.Pointer<ffi.WChar>,
        ffi.Pointer<ffi.UnsignedInt>)>()
external int ncplane_putwc_utf32(
  ffi.Pointer<main.ncplane> n,
  ffi.Pointer<ffi.WChar> w,
  ffi.Pointer<ffi.UnsignedInt> wchars,
);

@ffi.Native<
    ffi.Int Function(ffi.Pointer<main.ncplane>, ffi.Int, ffi.Int, ffi.WChar)>()
external int ncplane_putwc_yx(
  ffi.Pointer<main.ncplane> n,
  int y,
  int x,
  int w,
);

@ffi.Native<
    ffi.Int Function(ffi.Pointer<main.ncplane>, ffi.Pointer<ffi.WChar>,
        ffi.Pointer<ffi.Size>)>()
external int ncplane_putwegc(
  ffi.Pointer<main.ncplane> n,
  ffi.Pointer<ffi.WChar> gclust,
  ffi.Pointer<ffi.Size> sbytes,
);

@ffi.Native<
    ffi.Int Function(ffi.Pointer<main.ncplane>, ffi.Int, ffi.Int,
        ffi.Pointer<ffi.WChar>, ffi.Pointer<ffi.Size>)>()
external int ncplane_putwegc_yx(
  ffi.Pointer<main.ncplane> n,
  int y,
  int x,
  ffi.Pointer<ffi.WChar> gclust,
  ffi.Pointer<ffi.Size> sbytes,
);

@ffi.Native<
    ffi.Int Function(ffi.Pointer<main.ncplane>, ffi.Pointer<ffi.WChar>)>()
external int ncplane_putwstr(
  ffi.Pointer<main.ncplane> n,
  ffi.Pointer<ffi.WChar> gclustarr,
);

@ffi.Native<
    ffi.Int Function(ffi.Pointer<main.ncplane>, ffi.Int, ffi.UnsignedInt,
        ffi.Pointer<ffi.WChar>)>()
external int ncplane_putwstr_aligned(
  ffi.Pointer<main.ncplane> n,
  int y,
  int align,
  ffi.Pointer<ffi.WChar> gclustarr,
);

@ffi.Native<
    ffi.Int Function(
        ffi.Pointer<main.ncplane>, ffi.Int, ffi.Int, ffi.Pointer<ffi.WChar>)>()
external int ncplane_putwstr_yx(
  ffi.Pointer<main.ncplane> n,
  int y,
  int x,
  ffi.Pointer<ffi.WChar> gclustarr,
);

@ffi.Native<
    ffi.Int Function(
        ffi.Pointer<main.ncplane>, ffi.UnsignedInt, ffi.UnsignedInt)>()
external int ncplane_resize_simple(
  ffi.Pointer<main.ncplane> n,
  int ylen,
  int xlen,
);

@ffi.Native<
    ffi.Int Function(ffi.Pointer<main.ncplane>, ffi.Uint16, ffi.Uint64,
        ffi.UnsignedInt, ffi.UnsignedInt, ffi.UnsignedInt)>()
external int ncplane_rounded_box(
  ffi.Pointer<main.ncplane> n,
  int styles,
  int channels,
  int ystop,
  int xstop,
  int ctlword,
);

@ffi.Native<
    ffi.Int Function(ffi.Pointer<main.ncplane>, ffi.Uint16, ffi.Uint64,
        ffi.UnsignedInt, ffi.UnsignedInt, ffi.UnsignedInt)>()
external int ncplane_rounded_box_sized(
  ffi.Pointer<main.ncplane> n,
  int styles,
  int channels,
  int ylen,
  int xlen,
  int ctlword,
);

@ffi.Native<
    ffi.Int Function(ffi.Pointer<main.ncplane>, ffi.UnsignedInt, ffi.Int)>()
external int ncplane_valign(
  ffi.Pointer<main.ncplane> n,
  int align,
  int r,
);

@ffi.Native<
    ffi.Int Function(
        ffi.Pointer<main.ncplane>, ffi.Pointer<nccell>, ffi.UnsignedInt)>()
external int ncplane_vline(
  ffi.Pointer<main.ncplane> n,
  ffi.Pointer<nccell> c,
  int len,
);

@ffi.Native<
    ffi.Int Function(
        ffi.Pointer<main.ncplane>, ffi.Pointer<ffi.Char>, va_list)>()
external int ncplane_vprintf(
  ffi.Pointer<main.ncplane> n,
  ffi.Pointer<ffi.Char> format,
  va_list ap,
);

@ffi.Native<ffi.Int Function(ffi.Int, ffi.UnsignedInt, ffi.Int)>()
external int notcurses_align(
  int availu,
  int align,
  int u,
);

@ffi.Native<ffi.Int Function(ffi.Pointer<main.notcurses>)>()
external int notcurses_mice_disable(
  ffi.Pointer<main.notcurses> n,
);

@ffi.Native<ffi.Int Function(ffi.Pointer<main.notcurses>)>()
external int notcurses_render(
  ffi.Pointer<main.notcurses> nc,
);

@ffi.Native<
    ffi.Pointer<main.ncplane> Function(
        ffi.Pointer<main.notcurses>,
        ffi.Pointer<main.ncplane_options>,
        ffi.Pointer<main.ncvisual>,
        ffi.Pointer<main.ncvisual_options>)>()
external ffi.Pointer<main.ncplane> ncvisualplane_create(
  ffi.Pointer<main.notcurses> nc,
  ffi.Pointer<main.ncplane_options> opts,
  ffi.Pointer<main.ncvisual> ncv,
  ffi.Pointer<main.ncvisual_options> vopts,
);

@ffi.Native<ffi.Pointer<main.ncplane> Function(ffi.Pointer<main.notcurses>)>()
external ffi.Pointer<main.ncplane> notcurses_bottom(
  ffi.Pointer<main.notcurses> n,
);

@ffi.Native<
    ffi.Pointer<main.ncplane> Function(ffi.Pointer<main.notcurses>,
        ffi.Pointer<ffi.UnsignedInt>, ffi.Pointer<ffi.UnsignedInt>)>()
external ffi.Pointer<main.ncplane> notcurses_stddim_yx(
  ffi.Pointer<main.notcurses> nc,
  ffi.Pointer<ffi.UnsignedInt> y,
  ffi.Pointer<ffi.UnsignedInt> x,
);

@ffi.Native<ffi.Pointer<main.ncplane> Function(ffi.Pointer<main.notcurses>)>()
external ffi.Pointer<main.ncplane> notcurses_top(
  ffi.Pointer<main.notcurses> n,
);

@ffi.Native<ffi.Uint16 Function(ffi.Pointer<nccell>)>()
external int nccell_styles(
  ffi.Pointer<nccell> c,
);

@ffi.Native<ffi.Uint32 Function(ffi.Pointer<nccell>)>()
external int nccell_bchannel(
  ffi.Pointer<nccell> cl,
);

@ffi.Native<ffi.Uint32 Function(ffi.Pointer<nccell>)>()
external int nccell_bg_alpha(
  ffi.Pointer<nccell> cl,
);

@ffi.Native<ffi.Uint32 Function(ffi.Pointer<nccell>)>()
external int nccell_bg_palindex(
  ffi.Pointer<nccell> cl,
);

@ffi.Native<ffi.Uint32 Function(ffi.Pointer<nccell>)>()
external int nccell_bg_rgb(
  ffi.Pointer<nccell> cl,
);

@ffi.Native<
    ffi.Uint32 Function(ffi.Pointer<nccell>, ffi.Pointer<ffi.UnsignedInt>,
        ffi.Pointer<ffi.UnsignedInt>, ffi.Pointer<ffi.UnsignedInt>)>()
external int nccell_bg_rgb8(
  ffi.Pointer<nccell> cl,
  ffi.Pointer<ffi.UnsignedInt> r,
  ffi.Pointer<ffi.UnsignedInt> g,
  ffi.Pointer<ffi.UnsignedInt> b,
);

@ffi.Native<ffi.Uint32 Function(ffi.Pointer<nccell>)>()
external int nccell_fchannel(
  ffi.Pointer<nccell> cl,
);

@ffi.Native<ffi.Uint32 Function(ffi.Pointer<nccell>)>()
external int nccell_fg_alpha(
  ffi.Pointer<nccell> cl,
);

@ffi.Native<ffi.Uint32 Function(ffi.Pointer<nccell>)>()
external int nccell_fg_palindex(
  ffi.Pointer<nccell> cl,
);

@ffi.Native<ffi.Uint32 Function(ffi.Pointer<nccell>)>()
external int nccell_fg_rgb(
  ffi.Pointer<nccell> cl,
);

@ffi.Native<
    ffi.Uint32 Function(ffi.Pointer<nccell>, ffi.Pointer<ffi.UnsignedInt>,
        ffi.Pointer<ffi.UnsignedInt>, ffi.Pointer<ffi.UnsignedInt>)>()
external int nccell_fg_rgb8(
  ffi.Pointer<nccell> cl,
  ffi.Pointer<ffi.UnsignedInt> r,
  ffi.Pointer<ffi.UnsignedInt> g,
  ffi.Pointer<ffi.UnsignedInt> b,
);

@ffi.Native<ffi.Uint32 Function(ffi.Uint32)>()
external int ncchannel_alpha(
  int channel,
);

@ffi.Native<ffi.Uint32 Function(ffi.Uint32)>()
external int ncchannel_rgb(
  int channel,
);

@ffi.Native<
    ffi.Uint32 Function(ffi.Uint32, ffi.Pointer<ffi.UnsignedInt>,
        ffi.Pointer<ffi.UnsignedInt>, ffi.Pointer<ffi.UnsignedInt>)>()
external int ncchannel_rgb8(
  int channel,
  ffi.Pointer<ffi.UnsignedInt> r,
  ffi.Pointer<ffi.UnsignedInt> g,
  ffi.Pointer<ffi.UnsignedInt> b,
);

@ffi.Native<ffi.Uint32 Function(ffi.Pointer<ffi.Uint32>)>()
external int ncchannel_set_default(
  ffi.Pointer<ffi.Uint32> channel,
);

@ffi.Native<ffi.Uint32 Function(ffi.Uint64)>()
external int ncchannels_bchannel(
  int channels,
);

@ffi.Native<ffi.Uint32 Function(ffi.Uint64)>()
external int ncchannels_bg_rgb(
  int channels,
);

@ffi.Native<
    ffi.Uint32 Function(ffi.Uint64, ffi.Pointer<ffi.UnsignedInt>,
        ffi.Pointer<ffi.UnsignedInt>, ffi.Pointer<ffi.UnsignedInt>)>()
external int ncchannels_bg_rgb8(
  int channels,
  ffi.Pointer<ffi.UnsignedInt> r,
  ffi.Pointer<ffi.UnsignedInt> g,
  ffi.Pointer<ffi.UnsignedInt> b,
);

@ffi.Native<ffi.Uint32 Function(ffi.Uint64)>()
external int ncchannels_fchannel(
  int channels,
);

@ffi.Native<ffi.Uint32 Function(ffi.Uint64)>()
external int ncchannels_fg_rgb(
  int channels,
);

@ffi.Native<
    ffi.Uint32 Function(ffi.Uint64, ffi.Pointer<ffi.UnsignedInt>,
        ffi.Pointer<ffi.UnsignedInt>, ffi.Pointer<ffi.UnsignedInt>)>()
external int ncchannels_fg_rgb8(
  int channels,
  ffi.Pointer<ffi.UnsignedInt> r,
  ffi.Pointer<ffi.UnsignedInt> g,
  ffi.Pointer<ffi.UnsignedInt> b,
);

@ffi.Native<
    ffi.Uint32 Function(ffi.Pointer<main.ncdirect>, ffi.Pointer<ncinput>)>()
external int ncdirect_get_blocking(
  ffi.Pointer<main.ncdirect> n,
  ffi.Pointer<ncinput> ni,
);

@ffi.Native<
    ffi.Uint32 Function(ffi.Pointer<main.ncdirect>, ffi.Pointer<ncinput>)>()
external int ncdirect_get_nblock(
  ffi.Pointer<main.ncdirect> n,
  ffi.Pointer<ncinput> ni,
);

@ffi.Native<
    ffi.Uint32 Function(ffi.UnsignedInt, ffi.UnsignedInt, ffi.UnsignedInt)>()
external int ncpixel(
  int r,
  int g,
  int b,
);

@ffi.Native<ffi.Uint32 Function(ffi.Pointer<main.ncplane>)>()
external int ncplane_bchannel(
  ffi.Pointer<main.ncplane> n,
);

@ffi.Native<ffi.Uint32 Function(ffi.Pointer<main.ncplane>)>()
external int ncplane_bg_alpha(
  ffi.Pointer<main.ncplane> n,
);

@ffi.Native<ffi.Uint32 Function(ffi.Pointer<main.ncplane>)>()
external int ncplane_bg_rgb(
  ffi.Pointer<main.ncplane> n,
);

@ffi.Native<
    ffi.Uint32 Function(ffi.Pointer<main.ncplane>, ffi.Pointer<ffi.UnsignedInt>,
        ffi.Pointer<ffi.UnsignedInt>, ffi.Pointer<ffi.UnsignedInt>)>()
external int ncplane_bg_rgb8(
  ffi.Pointer<main.ncplane> n,
  ffi.Pointer<ffi.UnsignedInt> r,
  ffi.Pointer<ffi.UnsignedInt> g,
  ffi.Pointer<ffi.UnsignedInt> b,
);

@ffi.Native<ffi.Uint32 Function(ffi.Pointer<main.ncplane>)>()
external int ncplane_fchannel(
  ffi.Pointer<main.ncplane> n,
);

@ffi.Native<ffi.Uint32 Function(ffi.Pointer<main.ncplane>)>()
external int ncplane_fg_alpha(
  ffi.Pointer<main.ncplane> n,
);

@ffi.Native<ffi.Uint32 Function(ffi.Pointer<main.ncplane>)>()
external int ncplane_fg_rgb(
  ffi.Pointer<main.ncplane> n,
);

@ffi.Native<
    ffi.Uint32 Function(ffi.Pointer<main.ncplane>, ffi.Pointer<ffi.UnsignedInt>,
        ffi.Pointer<ffi.UnsignedInt>, ffi.Pointer<ffi.UnsignedInt>)>()
external int ncplane_fg_rgb8(
  ffi.Pointer<main.ncplane> n,
  ffi.Pointer<ffi.UnsignedInt> r,
  ffi.Pointer<ffi.UnsignedInt> g,
  ffi.Pointer<ffi.UnsignedInt> b,
);

@ffi.Native<
    ffi.Uint32 Function(ffi.Pointer<main.notcurses>, ffi.Pointer<ncinput>)>()
external int notcurses_get_blocking(
  ffi.Pointer<main.notcurses> n,
  ffi.Pointer<ncinput> ni,
);

@ffi.Native<
    ffi.Uint32 Function(ffi.Pointer<main.notcurses>, ffi.Pointer<ncinput>)>()
external int notcurses_get_nblock(
  ffi.Pointer<main.notcurses> n,
  ffi.Pointer<ncinput> ni,
);

@ffi.Native<ffi.Uint64 Function(ffi.Pointer<nccell>)>()
external int nccell_channels(
  ffi.Pointer<nccell> c,
);

@ffi.Native<ffi.Uint64 Function(ffi.Pointer<nccell>, ffi.Uint32)>()
external int nccell_set_bchannel(
  ffi.Pointer<nccell> c,
  int channel,
);

@ffi.Native<ffi.Uint64 Function(ffi.Pointer<nccell>, ffi.Uint64)>()
external int nccell_set_channels(
  ffi.Pointer<nccell> c,
  int channels,
);

@ffi.Native<ffi.Uint64 Function(ffi.Pointer<nccell>, ffi.Uint32)>()
external int nccell_set_fchannel(
  ffi.Pointer<nccell> c,
  int channel,
);

@ffi.Native<ffi.Uint64 Function(ffi.Uint64)>()
external int ncchannels_channels(
  int channels,
);

@ffi.Native<ffi.Uint64 Function(ffi.Uint32, ffi.Uint32)>()
external int ncchannels_combine(
  int fchan,
  int bchan,
);

@ffi.Native<ffi.Uint64 Function(ffi.Uint64)>()
external int ncchannels_reverse(
  int channels,
);

@ffi.Native<ffi.Uint64 Function(ffi.Pointer<ffi.Uint64>, ffi.Uint32)>()
external int ncchannels_set_bchannel(
  ffi.Pointer<ffi.Uint64> channels,
  int channel,
);

@ffi.Native<ffi.Uint64 Function(ffi.Pointer<ffi.Uint64>)>()
external int ncchannels_set_bg_default(
  ffi.Pointer<ffi.Uint64> channels,
);

@ffi.Native<ffi.Uint64 Function(ffi.Pointer<ffi.Uint64>, ffi.Uint64)>()
external int ncchannels_set_channels(
  ffi.Pointer<ffi.Uint64> dst,
  int channels,
);

@ffi.Native<ffi.Uint64 Function(ffi.Pointer<ffi.Uint64>, ffi.Uint32)>()
external int ncchannels_set_fchannel(
  ffi.Pointer<ffi.Uint64> channels,
  int channel,
);

@ffi.Native<ffi.Uint64 Function(ffi.Pointer<ffi.Uint64>)>()
external int ncchannels_set_fg_default(
  ffi.Pointer<ffi.Uint64> channels,
);

@ffi.Native<ffi.Uint64 Function(ffi.Pointer<main.nctabbed>)>()
external int nctabbed_hdrchan(
  ffi.Pointer<main.nctabbed> nt,
);

@ffi.Native<ffi.Uint64 Function(ffi.Pointer<main.nctabbed>)>()
external int nctabbed_selchan(
  ffi.Pointer<main.nctabbed> nt,
);

@ffi.Native<ffi.Uint64 Function(ffi.Pointer<main.nctabbed>)>()
external int nctabbed_sepchan(
  ffi.Pointer<main.nctabbed> nt,
);

@ffi.Native<ffi.UnsignedInt Function(ffi.Pointer<nccell>)>()
external int nccell_cols(
  ffi.Pointer<nccell> c,
);

@ffi.Native<ffi.UnsignedInt Function(ffi.Uint32)>()
external int ncchannel_b(
  int channel,
);

@ffi.Native<ffi.UnsignedInt Function(ffi.Uint32)>()
external int ncchannel_g(
  int channel,
);

@ffi.Native<ffi.UnsignedInt Function(ffi.Uint32)>()
external int ncchannel_palindex(
  int channel,
);

@ffi.Native<ffi.UnsignedInt Function(ffi.Uint32)>()
external int ncchannel_r(
  int channel,
);

@ffi.Native<ffi.UnsignedInt Function(ffi.Uint64)>()
external int ncchannels_bg_alpha(
  int channels,
);

@ffi.Native<ffi.UnsignedInt Function(ffi.Uint64)>()
external int ncchannels_bg_palindex(
  int channels,
);

@ffi.Native<ffi.UnsignedInt Function(ffi.Uint64)>()
external int ncchannels_fg_alpha(
  int channels,
);

@ffi.Native<ffi.UnsignedInt Function(ffi.Uint64)>()
external int ncchannels_fg_palindex(
  int channels,
);

@ffi.Native<ffi.UnsignedInt Function(ffi.Uint32)>()
external int ncpixel_a(
  int pixel,
);

@ffi.Native<ffi.UnsignedInt Function(ffi.Uint32)>()
external int ncpixel_b(
  int pixel,
);

@ffi.Native<ffi.UnsignedInt Function(ffi.Uint32)>()
external int ncpixel_g(
  int pixel,
);

@ffi.Native<ffi.UnsignedInt Function(ffi.Uint32)>()
external int ncpixel_r(
  int pixel,
);

@ffi.Native<ffi.UnsignedInt Function(ffi.Pointer<main.ncplane>)>()
external int ncplane_cursor_x(
  ffi.Pointer<main.ncplane> n,
);

@ffi.Native<ffi.UnsignedInt Function(ffi.Pointer<main.ncplane>)>()
external int ncplane_cursor_y(
  ffi.Pointer<main.ncplane> n,
);

@ffi.Native<ffi.UnsignedInt Function(ffi.Pointer<main.ncplane>)>()
external int ncplane_dim_x(
  ffi.Pointer<main.ncplane> n,
);

@ffi.Native<ffi.UnsignedInt Function(ffi.Pointer<main.ncplane>)>()
external int ncplane_dim_y(
  ffi.Pointer<main.ncplane> n,
);

@ffi.Native<ffi.Void Function(ffi.Pointer<nccell>)>()
external void nccell_init(
  ffi.Pointer<nccell> c,
);

@ffi.Native<ffi.Void Function(ffi.Pointer<nccell>, ffi.UnsignedInt)>()
external void nccell_off_styles(
  ffi.Pointer<nccell> c,
  int stylebits,
);

@ffi.Native<ffi.Void Function(ffi.Pointer<nccell>, ffi.UnsignedInt)>()
external void nccell_on_styles(
  ffi.Pointer<nccell> c,
  int stylebits,
);

@ffi.Native<ffi.Void Function(ffi.Pointer<nccell>)>()
external void nccell_set_bg_default(
  ffi.Pointer<nccell> c,
);

@ffi.Native<ffi.Void Function(ffi.Pointer<nccell>, ffi.Int, ffi.Int, ffi.Int)>()
external void nccell_set_bg_rgb8_clipped(
  ffi.Pointer<nccell> cl,
  int r,
  int g,
  int b,
);

@ffi.Native<ffi.Void Function(ffi.Pointer<nccell>)>()
external void nccell_set_fg_default(
  ffi.Pointer<nccell> c,
);

@ffi.Native<ffi.Void Function(ffi.Pointer<nccell>, ffi.Int, ffi.Int, ffi.Int)>()
external void nccell_set_fg_rgb8_clipped(
  ffi.Pointer<nccell> cl,
  int r,
  int g,
  int b,
);

@ffi.Native<ffi.Void Function(ffi.Pointer<nccell>, ffi.UnsignedInt)>()
external void nccell_set_styles(
  ffi.Pointer<nccell> c,
  int stylebits,
);

@ffi.Native<
    ffi.Void Function(ffi.Pointer<ffi.Uint32>, ffi.Int, ffi.Int, ffi.Int)>()
external void ncchannel_set_rgb8_clipped(
  ffi.Pointer<ffi.Uint32> channel,
  int r,
  int g,
  int b,
);

@ffi.Native<
    ffi.Void Function(ffi.Pointer<ffi.Uint64>, ffi.Int, ffi.Int, ffi.Int)>()
external void ncchannels_set_bg_rgb8_clipped(
  ffi.Pointer<ffi.Uint64> channels,
  int r,
  int g,
  int b,
);

@ffi.Native<
    ffi.Void Function(ffi.Pointer<ffi.Uint64>, ffi.Int, ffi.Int, ffi.Int)>()
external void ncchannels_set_fg_rgb8_clipped(
  ffi.Pointer<ffi.Uint64> channels,
  int r,
  int g,
  int b,
);

@ffi.Native<ffi.Void Function(ffi.Pointer<main.ncplane>)>()
external void ncplane_move_bottom(
  ffi.Pointer<main.ncplane> n,
);

@ffi.Native<ffi.Void Function(ffi.Pointer<main.ncplane>)>()
external void ncplane_move_family_bottom(
  ffi.Pointer<main.ncplane> n,
);

@ffi.Native<ffi.Void Function(ffi.Pointer<main.ncplane>)>()
external void ncplane_move_family_top(
  ffi.Pointer<main.ncplane> n,
);

@ffi.Native<ffi.Void Function(ffi.Pointer<main.ncplane>)>()
external void ncplane_move_top(
  ffi.Pointer<main.ncplane> n,
);

@ffi.Native<
    ffi.Void Function(ffi.Pointer<main.notcurses>, ffi.Pointer<ffi.UnsignedInt>,
        ffi.Pointer<ffi.UnsignedInt>)>()
external void notcurses_term_dim_yx(
  ffi.Pointer<main.notcurses> n,
  ffi.Pointer<ffi.UnsignedInt> rows,
  ffi.Pointer<ffi.UnsignedInt> cols,
);

typedef nccapabilities = main.nccapabilities;
typedef nccell = main.nccell;
typedef ncinput = main.ncinput;
typedef uintmax_t = ffi.UnsignedLong;
typedef Dartuintmax_t = int;
typedef ncpalette = main.ncpalette;

sealed class ncalign_e {
  static const NCALIGN_UNALIGNED = 0;
  static const NCALIGN_LEFT = 1;
  static const NCALIGN_CENTER = 2;
  static const NCALIGN_RIGHT = 3;
}

typedef va_list = ffi.Pointer<ffi.Char>;
